### ISSUE TITLE
Is Devise susceptible to unicode Case Mapping Collisions?

### ISSUE THREAD

**Issue by jaredlt** [heartcombo/devise#5171]
As per this recent blog post: https://eng.getwisdom.io/hacking-github-with-unicode-dotless-i/ is Devise susceptible to the same attack?

```ruby
# Note the Turkish dotless i in 'Gıthub'
'John@Gıthub.com'.toLowerCase() === 'John@Github.com'.toLowerCase() # true
```

Essentially, Github were doing:

```ruby
user = get_user_from_valid_email(params[:email])
send_reset_email(params[:email])
# instead of
# send_reset_email(user.email)
```

ref: https://news.ycombinator.com/item?id=21809390

I am not proficient enough to inspect the Devise source myself but figured it would be safer to ask the question than not.

**Comment by rahearn** [comment]
Based on https://github.com/heartcombo/devise/blob/83a32e6d2118b0535cf54b48df4f9853d85b55fd/lib/devise/mailers/helpers.rb#L34 it appears that devise properly sends email to the saved resource email address
