### ISSUE TITLE
remember_me option break sign_in

### ISSUE THREAD

**Issue by UICJohn** [heartcombo/devise#5200]
## Environment

- Ruby **2.6.5**
- Rails **6.0.2.1**
- Devise **4.7**

## Current behavior
When check **remember me** in login form, login failed with no error provided,  login process looks good in console and page was redirect to root page with 200 OK. But current_user returning nil.  I am sure both email and password are correct. 

The params passed to server looks good: 
`{"authenticity_token"=>"tokenblablabl", "user"=>{"email"=>"me@email.com", "password"=>"[FILTERED]", "remember_me"=>"1"}, "commit"=>"Log in"}`

Login is successful if  **remember me** unchecked.

## Expected behavior
It should allow me to login no matter  I check the **remember me** button or not.

**Comment by UICJohn** [comment]
Actually, this code block will also stop the user from login.
`class User < ApplicationRecord`
`def remember_me true end`
`end`

**Comment by UICJohn** [comment]
The problem solved after I update devise from 4.7 to 4.7.1

**Comment by amseledka** [comment]
having the same issue on 
devise **4.7.1**
rails **5.0.7.2**
ruby **2.6.5**

code block above fixes the issue but seems hack-ish

Remember me broke update Devise update from **4.6.0** to **4.7.1**

**Comment by amseledka** [comment]
weirdly but updating nokogiri to the **1.10.9**  version fixes the issue!

`Installing nokogiri 1.10.9 (was 1.10.8)`
