### ISSUE TITLE
Cannot override opts[:from]

### ISSUE THREAD

**Issue by Sprachprofi** [heartcombo/devise#5205]
I'm using Devise 4.7.1 with Rails 5.2.0.

I have created my own Devise mailer and I have successfully swapped out the template and subject line on occasion, seems to be working fine. Now I need to my confirmation_instructions to switch to a different sending domain in case users are registering from that domain. I use 

opts[:from] = "info@mera25.gr"

as described in the Howto. **The Rails Mailer Preview also shows the email coming from that address.  In fact, I can call MyDeviseMailer.confirmation_instructions(User.last, "falsetoken", {}) in the console and it will send from that domain.** The only place it doesn't work is when people actually register, so the same User.last got an automatic confirmation email from the wrong domain and then a console-induced confirmation email from the right domain. It seems that something is overwriting opts[:from] later in the process?!

**Comment by Sprachprofi** [comment]
In order to monkeypatch, I tried to re-open the Confirmable class and overwrite the function that sends out those emails in order to tell it to use my other mailer, but this does not seem to have any effect. I'd greatly appreciate help in fixing the original issue or doing a successful monkeypatch.

**Comment by nashby** [comment]
Hey, it's hard to understand why it's not properly working for you without any sample app where we can reproduce this issue. Could you please send one if it's still an issue for you?
