### ISSUE TITLE
Built in  support for neo4j database with activegraph gem

### ISSUE THREAD

**Issue by amitsuryavanshi** [heartcombo/devise#5206]
I am thinking about having a built in support in devise for neo4j database with activegraph gem. Would like to get thoughts from maintainers. The current `devise-neo4j` gem needs some maintenance work, so was thinking if I can just do it in devise gem.

**Comment by rafaelfranca** [comment]
Thank you for the suggestion but we have no interest on maintaining neo4j integration in the devise gem. I recommend you to build a separated gem as plugin. I'm open to make changes to make devise more easy to implement a neo4j integration if needed though.

**Comment by amitsuryavanshi** [comment]
Okay. I will work on existing `devise-neo4j` gem. Thanks for your thoughts @rafaelfranca
