### ISSUE TITLE
ActionController::InvalidAuthenticityToken error still exists when deploying to Heroku

### ISSUE THREAD

**Issue by faraazahmad** [heartcombo/devise#5207]
## Environment

- Ruby **2.6.3**
- Rails **6.0.2**
- Devise **4.7.1**

## Current behavior

After deploying my Rails app with Devise authentication to Heroku, registering a user or signing in throws `ActionController::InvalidAuthenticityToken`. I tried adding `protect_from_forgery prepend: true, with: :exception` to `ApplicationController` and that doesn't fix it. I tried the hacky way of using

```ruby
skip_before_action :verify_authenticity_token, if: -> { controller_name.include? 'sessions' }
skip_before_action :verify_authenticity_token, if: -> { controller_name.include? 'registrations' }
```
and now I can register and sign in but then the error occurs on controller methods where I call `before_action :authenticate_user!`. I even tried adding `protect_from_forgery prepend: true, with: :exception` before every call of `authenticate_user!` but the error still occurs.

Trust me I've seen and tried all the solutions given on SO and closed issues over here on this issue, none of them seems to solve it.

## Expected behavior

The error should not occur.

**Comment by faraazahmad** [comment]
Turns out it's an issue with Cloudfare DNS.

https://github.com/rails/rails/issues/22965#issuecomment-336190639
It's now solved, thanks to @nunosilva800

**Comment by mohitahlawat2001** [comment]
hii 'im getting this ActionController::InvalidAuthenticityToken error how i can solve this
![image](https://user-images.githubusercontent.com/65100859/115496903-41e96980-a288-11eb-9ab6-0c9d68c9fa2b.png)
![Screenshot 2021-04-19 212152](https://user-images.githubusercontent.com/65100859/115496944-57f72a00-a288-11eb-9c2c-d77dde08eec9.jpg)
