### ISSUE TITLE
Sign in/up routing error

### ISSUE THREAD

**Issue by thubamamba** [heartcombo/devise#5209]
![Screenshot 2020-03-14 at 01 44 18](https://user-images.githubusercontent.com/22769109/76669703-84287d80-6595-11ea-9a4a-5351f61b96fe.png)

My sign up and sign in pages using devise show the year 2020. This just happened on a new project I just set up and one that is in production. Please help assist. Might it perhaps be the devise version I am using?

## Environment

- Ruby **2.6.3p62**
- Rails **6.0.2.1**
- Devise **4.7.1**

## Current behavior

On clicking either of the mentioned pages, instead of the form showing the year 2020 shows and you have to refresh in order for you to see the form. 
Here's an app I have in production with the same case: http://satechjobs.co.za/

**Comment by nashby** [comment]
@thubamamba Sorry for late response. Looks like it's something related to your app and not devise specific. If it's still an issue please send us an app that reproduces this issue. Thanks!
