### ISSUE TITLE
env['devise.skip_tracking'] for polling requests

### ISSUE THREAD

**Issue by Mihran9991** [heartcombo/devise#5217]
I'm using long polling for checking whether user session expired or not for auto logout, but   every time I make request session expiration date is getting expanded and skip_trackable not helping. 
```
  before_action :skip_trackable, only: [:session_status]

  def session_status
    puts "session_status"
    ... some stuff
  end

  protected

  def skip_trackable
    request.env['warden'].request.env['devise.skip_trackable'] = '1'
   # OR request.env['devise.skip_trackable'] = true also not working
  end
```

**Comment by nashby** [comment]
I think you need to use `prepend_before_action` if you want to set `skip_trackable` before Devise does trackable logic.
