### ISSUE TITLE
Reconfirmation page does nothing

### ISSUE THREAD

**Issue by martino-dot** [heartcombo/devise#5220]
## Environment

- Ruby **2.6.3p63**
- Rails **6.0.2.2**
- Devise **4.7.0**

## Current behavior

Submitting email for reconfirmation does not work, and doesn't actually send anything. The first confirmation email does work and you can confirm it, but if you need to send it again, it doesn't work. 
**Console Log**
```
Started POST "/users/confirmation" for 10.0.0.9 at 2020-04-14 21:57:52 +0000
Processing by Devise::ConfirmationsController#create as HTML
  Parameters: {"authenticity_token"=>"tokenstring", "user"=>{"email"=>"example@example.org"}, "commit"=>"Resend confirmation"}
  Rendering devise/confirmations/new.html.erb within layouts/application
  Rendered devise/confirmations/new.html.erb within layouts/application (Duration: 1.6ms | Allocations: 306)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 71ms (Views: 25.9ms | ActiveRecord: 0.0ms | Allocations: 14515)
```

## Expected behavior

Sends an email out to the user to reconfirm their email address.

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by martino-dot** [comment]
That's weird, I cannot replicate it and it works fine on a new installation.

**Comment by rafaelfranca** [comment]
If you can't reproduce in a new app the problem could be in your application. It is hard to us to help if we can't know how to reproduce.

**Comment by martino-dot** [comment]
I fixed it! If anyone has the same problem (at least for me) you just have to uninstall devise and reinstall it afterwords. Make sure to copy the folder and everything just in case something goes wrong, but if you don't want to do that I would also recommend you to compare your files with the original Devise files. This makes sure you don't have something in your devise.rb initializer file that you forgot to remove.
