### ISSUE TITLE
Get session id (/cookie value) programmatically in a controller after doing sign_in

### ISSUE THREAD

**Issue by ndvbd** [heartcombo/devise#5228]
How can we get the *new* session id or set-cookie value after doing sign_in ?

Using` cookies[COOKIE_NAME]`, or `request.session_options[:id]` bring the old cookie value.
I saw that Devise changes the session id after authentication.

The `headers` object doesn't even show the 'Set-Cookie' attribute.

It feels like Devise/Warden is doing something under the hood, but I need to be able to get the new session idea (the value of the Set-Cookie HTTP header), before it is sent to the client.

**Comment by carlosantoniodasilva** [comment]
Closing, let us know if you're still running into any issue there.
