### ISSUE TITLE
Doubt: Maintenance status and release frequency

### ISSUE THREAD

**Issue by pedrofurtado** [heartcombo/devise#5230]
Hey everyone!

I have a doubt: After changing ownership of the repositories from "Plataformatec" to "Heartcombo", the frequency of released versions and commits decreased. Is this normal due to the transition period? Or will there be any changes to the maintenance guidelines?

Anyway, thanks for these gems and your work on it!

🤝

**Comment by rafaelfranca** [comment]
Everything is like it was before. The release will happen when it is ready and the commits will be made when needed.
