### ISSUE TITLE
Warning controller_helpers.rb:35: 

### ISSUE THREAD

**Issue by VitaliiLazebnyi** [heartcombo/devise#5234]
## Environment

- Ruby **2.7.1**
- Rails **6.0.3**
- Devise **master** (March 8 2020)

## Current behavior
`~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/devise-70f3ae24e009/lib/devise/test/controller_helpers.rb:36: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-controller-testing-a60b3da1c1c7/lib/rails/controller/testing/template_assertions.rb:60: warning: The called method process' is defined here`

gemfile:
`gem 'devise', git: 'git@github.com:heartcombo/devise.git'`

Current code:
> 34:       def process(*)
> 35:         _catch_warden { super }
> 36: 
> 37:         @response
> 38:       end

## Expected behavior
no warnings

**Comment by VitaliiLazebnyi** [comment]
PR: https://github.com/heartcombo/devise/pull/5214

**Comment by VitaliiLazebnyi** [comment]
PR https://github.com/heartcombo/devise/pull/5235
this one works with older Ruby.

**Comment by carlosantoniodasilva** [comment]
Closed by #5235, cherry-picked to master on https://github.com/heartcombo/devise/commit/e0b9915418ee71e6531c6b84ed3a1dad2eb981cf. Thanks!
