### ISSUE TITLE
Can not use devise in a test/dummy app run in a 'test' env - current_user is undefined

### ISSUE THREAD

**Issue by thebravoman** [heartcombo/devise#5237]
## Environment

- Ruby 2.6.5
- Rails 6.0.3
- Devise 4.7.1

## Current behavior
Create an full engine and try to use devise current use it the test dummy app when the app is run in a 'test' env. 

Demonstration app available at https://github.com/thebravoman/dev_dum.git

```bash
$ rails plugin new dev_dum --full
$ cd dev_dum
```

Fix todos in gemspecs
Add to gemspec.

```
spec.add_dependency 'devise'
spec.add_development_dependency 'devise'
spec.add_development_dependency 'rspec-rails'
spec.add_development_dependency 'capybara'
spec.add_development_dependency 'selenium-webdriver'
```

```
$ bundle install
$ cd test/dumy
$ echo 'class TestController < ApplicationController 
 def index
  current_user
 end
end' > app/controllers/test_controller.rb
$ rails generate devise:install
$ rails generate devise User
      invoke  active_record
      create    db/migrate/20200518151259_devise_create_users.rb
      create    app/models/user.rb
      invoke    rspec
      create      spec/models/user_spec.rb
      insert    app/models/user.rb
       route  devise_for :users
$ rails db:migrate
```

Add 'root to: "test#index" ' to config/routes.rb

Create app/views/test/index.html.erb
```bash
$ mkdir app/views/test
$ echo 'fun' > app/views/test/index.html.erb
```

Start server
```bash
$ rails s -p 3007
=> Booting WEBrick
=> Rails 6.0.3 application starting in development http://localhost:3007
=> Run `rails server --help` for more startup options
[2020-05-18 18:14:54] INFO  WEBrick 1.4.2
[2020-05-18 18:14:54] INFO  ruby 2.6.5 (2019-10-01) [x86_64-linux]
[2020-05-18 18:14:54] INFO  WEBrick::HTTPServer#start: pid=23221 port=3007
```

Go to the page and you see fun

But now start with test env
```bash
$ RAILS_ENV=test rails s -p 3007
=> Booting WEBrick
=> Rails 6.0.3 application starting in test http://0.0.0.0:3007
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
...
/tmp/dev_dum/test/dummy/config/initializers/devise.rb:5:in `<top (required)>': uninitialized constant Devise (NameError)
```

Add 'require "devise"' to config/initializers/devise.rb
Configure
```
Devise.setup do |config|
  config.secret_key = '7580e3651eab6165afcb385528badec607b8a603f846e11c63fb4d51c14887e17c8e684c6b9d1d6bc7dc0d22fd4cf009c8a0153649efc8b34903fc957f9696fe'
```

Start again with RAILS_ENV=test
Visit localhost:3007

Error occurs.

```
Internal Server Error
undefined local variable or method `current_user' for #<TestController:0x0000563f132d43c8>
```
## Expected behavior

I would expect the current user to be available in test env

**Comment by thebravoman** [comment]
I found a solution/workaround for this. Thinking about spec.add_dependency and spec.add_development_dependency I went on to add the devise directly in the Gemfile

```
gem 'devise'
```

I could live with this. I was just not expecting it. Is this the way devise should be used in a test/dummy. 
Probably this applies also to other gems, that we need in a test env which leads to a redundancy between Gemfile and gemspec, but I guess this is more of a question for the rails team - found this details on the matter https://github.com/rubygems/rubygems/issues/1104

**Comment by nashby** [comment]
@thebravoman hey! If you don't add "devise" to Gemfile you have to require it at proper time. I can see that you require it in `config/initializers/devise.rb` but you have to do it earlier, e.g in `config/application.rb` (that's where bundler requires all the gems from Gemfile). I tested it now and it worked as expected.
