### ISSUE TITLE
Don't use GET for account confirmation

### ISSUE THREAD

**Issue by pupeno** [heartcombo/devise#5241]
When using Devise to build APIs, it's a bit odd that some end points that modify the database use `GET` vebs, for example:

```
user_confirmation GET    /api/v1/users/confirmation(.:format)                                                     devise/confirmations#show {:format=>:json}
      user_unlock GET    /api/v1/users/unlock(.:format)                                                           devise/unlocks#show {:format=>:json}
```

On an API these should probably be PUT, POST or PATCH.

**Comment by rafaelfranca** [comment]
Thank you for the issue. Those two routes were made to be clicked in emails, so they need to use the GET verb. If this doesn't work for your API you can define the routes yourself
