### ISSUE TITLE
Per resource email address

### ISSUE THREAD

**Issue by pupeno** [heartcombo/devise#5244]
For multi-tenant applications or applications in which there are many resources, I think it would be useful if Device allowed to define the from email address per resource instead of globally.

**Comment by rafaelfranca** [comment]
This should be already possible. You can set the [`Devise.mailer_sender` config](https://github.com/heartcombo/devise/blob/70f3ae24e00906814b63fe1998c861ca45fbecf6/lib/devise.rb#L211) to a proc that receive the resource name and return an different address per resource.
