### ISSUE TITLE
Devise translations not working.

### ISSUE THREAD

**Issue by alu0100921038** [heartcombo/devise#5246]
## Environment

- Ruby **[2.1.2]**
- Rails **[4.2.7.1]**
- Devise **[3.5.10]**

## Current behavior

So i finished with the translations of my project with i18n. For the devise messages, i just created a new file called, devise.es.yml, and placed there all the translations in spanish. The rest of my project is working, but, with the devise i have some weird behaviour, because sometimes i get messages in english when im in spanish and viceversa. So, i have some view that renders the errors messages in the login page:

```
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String)%>
    <div class="alert alert-<%= name.to_sym == :notice ? 'success' : 'danger' %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, content_tag(:ul, msg.html_safe, class: "clear"), :id => "flash_#{name}" %>
    </div>
  <% elsif msg.is_a?(Array) %>
    <div class="alert alert-<%= name.to_sym == :notice ? 'success' : 'danger' %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, content_tag(:ul, "<li>#{msg.join('</li><li>')}</li>".html_safe, class: "clear"), :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
```

So, even if the language in that view is spanish, sometimes, i already have messages in english inside the flash variable. The thing is, i imagined there would be somewhere in the project where that variable is being setted, with messages like t('devise.failure.unauthenticated'), but i saw this is nowhere in the project. So i dont know what is the problem. I have messages that i dont know where they are being assigned to the flash variable, and from what i read, to translate things from devise, it is just creating the other file devise.es.yml.

![image](https://user-images.githubusercontent.com/22820644/82664118-eb634d80-9c28-11ea-87fa-11f7b7723c53.png)

There, everything is correct except for the message error, which is in english, and im having a hard time figuring out why this happens.

Sorry if my problem is not clear, english is not my first language. Thanks to whoever can help me.

**Comment by carlosantoniodasilva** [comment]
Hey, I finally have a PR up with this change: https://github.com/heartcombo/devise/pull/5567, if you happen to still be having this issue and want to give it a shot, let me know if you run into any issues.
