### ISSUE TITLE
devise_group not working Rails 6.0.2|Ruby 2.6.5|Devise 4.7.1

### ISSUE THREAD

**Issue by epipheus** [heartcombo/devise#5248]
## Environment

Rails 6.0.1
Ruby 2.6.5
Devise 4.7.1

## Current behavior
In my application controller I have:
```ruby 
devise_group 	:user, contains: [:investor, :founder, :squad, :general]
```
however, stepping through my controller I found that current_user is null but current_general is present.  This is causing a real problem

## Expected behavior
I thought the whole point of `devise_group` was to allow STI current_[parent_name] in this case current_user to access the user regardless of type.  

What am I missing here?

**Comment by epipheus** [comment]
Actually, I think there's something weird going on, let me make a simple example reproducing this.

**Comment by epipheus** [comment]
yes, an annoying Application Controller include mucked with current_user.  Closing.

**Comment by hurda21** [comment]
What was the instance here? Running into something similar where the group is being ignored even though it's defined in ApplicationController.
