### ISSUE TITLE
Suggestion: Formal documentation on how to log authentication activities

### ISSUE THREAD

**Issue by DannyBen** [heartcombo/devise#5249]
Hello,

I spent quite a lot of time searching Google, GitHub and StackOverflow for an official and easy way to do something (in my case, log) on these events:

- Successful sign in
- Failed sign in
- Sign out

There are quite a few complex (and in my view, risky) options like subclassing `Devise::SessionController` and other solutions that only solve part of the requirements.

I would like to suggest this:

1. If would be nice if Devise itself can provide configuration option or callbacks that can be defined on the `User` model to capture these events.
2. An alternative - if the above is not desired - is to provide a Wiki article about it (I am willing to contribute it, if the solution I found below is acceptable).

The easiest way I found to do it, is to create an initializer and place this code in it:

```ruby
# config/initializers/warden.rb
# Log authentication activities
# Docs: https://www.rubydoc.info/github/hassox/warden/Warden/Hooks

Warden::Manager.after_set_user except: :fetch do |user, auth, opts|
  $warden_log.info "Successful sign in by #{user.log_entry}"
end

Warden::Manager.before_failure do |env, opts|
  email = Rack::Request.new(env).params['user']['email']
  $warden_log.info "Failed sign in by #{email}"
rescue => e
  $warden_log.error "[Warden::Manager.before_failure] #{e.class}: #{e.message}"
end

Warden::Manager.before_logout do |user, auth, opts|
  $warden_log.info "Successful sign out by #{user.log_entry}"
end
```

Assuming this way of doing it makes sense, should I add the wiki page?

**Comment by evolve2k** [comment]
Sounds really good to me and very useful for many people. That's what a wiki is for. I'd say add it in 🙌

**Comment by evolve2k** [comment]
YES Add to wki.

_Recommend close._

**Comment by DannyBen** [comment]
So I guess the first part of my suggestion didn't pass?

> If would be nice if Devise itself can provide configuration option or callbacks that can be defined on the User model to capture these events.

It would be much nicer to define this without resorting to `Warden::Manager` hooks, since Devise users installed Devise, and I can speak for most of them when I am saying they do not want to deal with Warden.

Perhaps this can even be aliased without much effort, even just to provide similarly named hooks, only under the Devise namespace.

In any case, I will close this for now, perhaps I will add a wiki page (it has been some time since I opened this issue). Feel free to reopen if there is any chance of improving the way users define these hooks in devise itself.
