### ISSUE TITLE
Email field attribute always assigns to blank

### ISSUE THREAD

**Issue by KelseyDH** [heartcombo/devise#5251]
I have a newly generated devise model I generated after using devise with ActiveAdmin (then removing it) that is blanking emails no matter what I do.

## Environment

- Ruby **[2.6.3p62]**
- Rails **[6.0.3.1]**
- Devise **[4.7.1]**

User.rb model:

```ruby
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable

  attr_accessor :email, :password, :password_confirmation, :remember_me

end
```

schema.rb:

```ruby
  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer "sign_in_count", default: 0, null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.inet "current_sign_in_ip"
    t.inet "last_sign_in_ip"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.boolean "superadmin", default: false, null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end
```

## Current behavior
Running this in my console:

```ruby
    User.create! do |r|
      r.email      = 'example@email.com'
      r.password   = 'password'
      r.superadmin = true
    end
```

or even just trying to assign a value to email with initialization, e.g.:

```
u = User.new
u.email = "example@email.com"
u
```

Returns user attributes with `email = ""`

## Expected behavior

The expectation is that `u.email = "something@example.com"` correctly assigns the email.

I am at a complete loss as to how I can even debug this issue when every attempt to assign email values fails.

**Comment by KelseyDH** [comment]
Weirdly, the issue went away after I changed my configuration to  what was recommended here: https://stackoverflow.com/questions/30249740/how-do-i-use-devise-and-activeadmin-for-the-same-user-model

and by adding:

```
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end
```

to my controller.

**Comment by nofxx** [comment]
Allow me to add this log error, maybe help someone in the future.

In our case we're using email OR phone to login, so sometimes email is not present, but devise set's it to `nil` thus it ends up in mongo as `null` and you get problems with unique sparse:

```
[11000]: E11000 duplicate key error collection: app_development.users index: email_1 dup key: { m: null } (on localhost:28017, legacy retry, attempt 1)
```

Solution is `unset(:email) if email.nil?`
