### ISSUE TITLE
Deprecation warning: Expected boolean default value for '--orm'; got :active_record (string). This will be rejected in the future unless you explicitly pass the options `check_default_type: false` or call `allow_incompatible_default_type!` in your code You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.

### ISSUE THREAD

**Issue by markovanderpuil** [heartcombo/devise#5252]
## Environment

- Ruby 2.7.1
- Rails 6.0.3
- Devise 4.7.2

## Current behavior

`rails generate devise User`

```
Deprecation warning: Expected boolean default value for '--orm'; got :active_record (string).
This will be rejected in the future unless you explicitly pass the options `check_default_type: false` or call `allow_incompatible_default_type!` in your code
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
```

## Expected behavior

No deprecation warning is presented.

**Comment by rafaelfranca** [comment]
This was caused by https://github.com/heartcombo/devise/pull/5215. I think we need to set `check_default_type`. Can you open a PR?

**Comment by deivid-rodriguez** [comment]
Using `required: true` as initially proposed by #5215 seems to do the trick.

**Comment by sreuterle** [comment]
When will this be published as new Gem version?

**Comment by carlosantoniodasilva** [comment]
@sreuterle I was planning on finalising a few other things before cutting a new release, due to some other deprecations already in master and others I was looking into. I'll see about the possibility of releasing a new one with just this fix this though.

**Comment by carlosantoniodasilva** [comment]
@sreuterle v4.7.3 is out including this change, thanks!
