### ISSUE TITLE
Directories not removed when destroying

### ISSUE THREAD

**Issue by hsul4n** [heartcombo/devise#5254]
## Environment
- Ruby **[2.6.3]**
- Rails **[6.0.3]**
- Devise **[4.7.1]**

## Current behavior
Directories not removed when trying to destroy, for example when running: `rails generate devise:views users` everything works fine but when try to destroy those views by running `rails destroy devise:views users` the subdirectories such as (users/confirmations, users/mailer, etc..) are not removed.

## Expected behavior
Should remove all views files and folder (directories) related to the user.

**Comment by Diego-Thomaz** [comment]
Hi there, well, I was thinking about this solution and I think we can have serious problems with non devise files that can exists inside these folders. Maybe if the expected behavior is a bit different, something like, Should remove empty folders after remove devise files makes more sense to me.

**Comment by carlosantoniodasilva** [comment]
This is basically functionality of the Rails generators, not specific to Devise. Also the folders are not committed to the repo unless they've something inside, so it's fine from git's perspective afaik.
