### ISSUE TITLE
`DeviseHelper.devise_error_messages!` is deprecated and it will be removed in the next major version.

### ISSUE THREAD

**Issue by evolve2k** [heartcombo/devise#5257]
## Environment

- Ruby 2.7 & Ruby 2.6
- Rails 5.2.4.3
- Devise 4.7.1

## Current behavior

Devise generating the following error message in my rails server logs:

DEPRECATION WARNING: [Devise] `DeviseHelper.devise_error_messages!` is deprecated and it will be removed in the next major version. To customize the errors styles please run `rails g devise:views` and modify the `devise/shared/error_messages` partial.

Second line recommends reviewing devise/shared/error_messages partial, but the partial provides no insight as to how to address the deprecation warning, seem this is maybe was intended to be a second unrelated notice?
```
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
```
## Expected behavior

Please provide an official explaination of why this was deprectaed and what is your recommended approach to resolving the deprecation warning.

**Comment by carlosantoniodasilva** [comment]
@evolve2k the helper has been moved to a partial in https://github.com/heartcombo/devise/pull/4616, and the deprecation might still be triggered if you're pointing to the helper in any of your previously generated views. Make sure to change the references from 

```
<%= devise_error_messages! %>
```

to

``` 
<%= render "devise/shared/error_messages", resource: resource %>
```

We might have to make that deprecation message a bit clearer about the steps there, but this should get rid of it.

**Comment by evolve2k** [comment]
Excellent thank you. And yes please update the deprecation warning to include the fix or a link to here.. That'd def help those that follow.
