### ISSUE TITLE
ClickHouse

### ISSUE THREAD

**Issue by Bdoom** [heartcombo/devise#5259]
#Environment

- Ruby **2.7**
- Rails **6.0.3.1**
- Devise **4.7.1**

## Current behavior

Has support for MongoDB, and PostgreSQL, SQLServer...etc

## Expected Behavior

Does Devise support clickhouse? https://clickhouse.tech/ 
https://github.com/PNixx/clickhouse-activerecord

**Comment by carlosantoniodasilva** [comment]
The database abstractions are provided by Rails (e.g. PostgreSQL, SQLServer, and it appears ClickHouse - never heard to it before). The ORM is still Active Record for those, another ORM is for MongoDB.

If it's still Active Record, there's nothing ORM or Devise specific about it, I believe it should work.
