### ISSUE TITLE
BCrypt::Errors::InvalidHash in Devise::RegistrationsController#create

### ISSUE THREAD

**Issue by riwaj-shrestha-iw** [heartcombo/devise#5266]
## Environment

- Ruby **[2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux] ]**
- Rails **[5.1.4]**
- Devise **[3.1.7]**

## Current behavior
Got this error when creating new user for my app.
![image](https://user-images.githubusercontent.com/64764984/87416435-6e33d380-c5ee-11ea-82c1-bdfb13ef80ee.png)

## Expected behavior
I want to create a simple user

**Comment by ponny** [comment]
@riwaj-shrestha-iw I started getting this.  What was the solution?
