### ISSUE TITLE
Is the name 'devise' under copyright?

### ISSUE THREAD

**Issue by ibraheemdev** [heartcombo/devise#5275]
I was wondering if the name 'devise' was under copyright or any other restrictions for use by another open-source project. If I were to reimplement devise in golang, would calling my project 'godevise' be okay? Could I use the logo? Would I have to include this project's license?

Edit: The logo seems to be under a CC license, but I can't find any copyright including the name, but I just want to make sure, thanks.

**Comment by carlosantoniodasilva** [comment]
It's not legally registered, however I'd consider it part of the project's license / copyright at this point. It's become a well-known project in the Ruby community after 10 years, I think it'd be rather confusing to have projects with the exact same name under different languages, from different authors. I wouldn't create a "rails" project in another language, for example.

That said, you are free to create variations of it that refer back, like the example `godevise` that you mentioned.

The logo can be used to refer to `devise` itself, or material/content related to it, given proper attributions are made, but not on different projects.
