### ISSUE TITLE
How to send reset password link to gmail ?

### ISSUE THREAD

**Issue by shubhamjain108-lab** [heartcombo/devise#5284]
i have install devise, need to send link to gmail so how do we do with devise?

**Comment by marcelolx** [comment]
@shubhamjain108-lab Have you included confirmable module to your user model? https://github.com/heartcombo/devise/wiki/How-To:-Add-:confirmable-to-Users

If you are using rails and already followed the instructions of the link above, i think what you haven't do is configuring smpt settings of action_mailer in development.rb/production.rb file, something like this:

```ruby
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  config.action_mailer.perform_caching = false
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.perform_deliveries = true
  config.action_mailer.smtp_settings = {
    address: SMPT_ADDRESS,
    port: SMPT_PORT,
    user_name: SENDER_USER_NAME,
    password: SENDER_PASSWORD,
    enable_starttls_auto: true
  }
```

Look at these example apps, maybe some will help you. https://github.com/heartcombo/devise/wiki/Example-applications

Also, take a look at these articles

https://dev.to/morinoko/sending-emails-in-rails-with-action-mailer-and-gmail-35g4
https://www.bogotobogo.com/RubyOnRails/RubyOnRails_Devise_Authentication_Sending_Confirmation_Email.php

If you need more help, i think stackoverflow will be the right place do search/ask how to do it https://stackoverflow.com/questions/tagged/devise

**Comment by shubhamjain108-lab** [comment]
@marcelolx marcelolx, thank you.
