### ISSUE TITLE
How to use devise to authorize user from my callback method? Like SSO

### ISSUE THREAD

**Issue by Drblack101** [heartcombo/devise#5292]
In my user controller, I have a callback (oauth2_callback) method (using 'oauth2' gem only) which is working and I can get user confirmation through 3rd party API. Once I validate this user is existing and matching my user in the DB, I want to perform SSO feature and let this user automatically sign in to the system. 

I have no idea how to continue to let devise to sign in my user after this step. Need some tips and guidance, please.

**Comment by carlosantoniodasilva** [comment]
I think you might be looking for the `sign_in` helper: https://github.com/heartcombo/devise/blob/eed641d2bea11839ab13e943660da41cad14314d/lib/devise/controllers/sign_in_out.rb#L19-L55

Hopefully that will work for your needs!
