### ISSUE TITLE
rails g device:install

### ISSUE THREAD

**Issue by arun2github** [heartcombo/devise#5299]
Afrter adding device gem in gemfile.
$ bundle install
$ rails g device:install
/usr/local/lib/ruby/2.7.0/x86_64-linux/stringio.so: warning: already initialized constant StringIO::VERSION
Running via Spring preloader in process 6989
Could not find generator 'device:install'. 
Run `rails generate --help` for more options.
..
now getting this issue also tried spring stop but didn't work

**Comment by tegon** [comment]
@arun2github Your error says `Could not find generator 'device:install'.` but it's devise with an `s` instead of `c`.
Can you try `rails g devise:install`?

**Comment by damuz91** [comment]
> @arun2github Your error says `Could not find generator 'device:install'.` but it's devise with an `s` instead of `c`.
> Can you try `rails g devise:install`?

Just had same issue but off course without that typo:
```
damuz91@MacBook-Pro-de-David-2 admin % rails g devise:install
Running via Spring preloader in process 16747
Deprecation warning: Expected string default value for '--controller'; got false (boolean).
This will be rejected in the future unless you explicitly pass the options `check_default_type: false` or call `allow_incompatible_default_type!` in your code
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
Could not find generator 'devise:install'. 
Run `rails generate --help` for more options.
```

**Comment by carlosantoniodasilva** [comment]
I'm gonna go ahead and close, please let us know if that still doesn't work and we can reopen.
