### ISSUE TITLE
Wiki: Someone messed with the how-to page "redirect to a specific page on successful sign in out"?

### ISSUE THREAD

**Issue by nodepond** [heartcombo/devise#5308]
It looks, like one how-to page in the wiki is messed. I wanted to read it, but all I got is a blank page.
https://github.com/heartcombo/devise/wiki/How-to:-redirect-to-a-specific-page-on-successful-sign-in-out/

Here is a history of the version.
https://github.com/heartcombo/devise/wiki/How-to:-redirect-to-a-specific-page-on-successful-sign-in-out/_history

This is the version, the page is currently showing:
https://github.com/heartcombo/devise/wiki/How-to:-redirect-to-a-specific-page-on-successful-sign-in-out/ffee6cbe8c51024d355fd1c24b9b77d975c4a20c

This is the version before the last commit (showing content):
https://github.com/heartcombo/devise/wiki/How-to:-redirect-to-a-specific-page-on-successful-sign-in-out/dfce49e7ab9d91e16d4919bdda6a2ecb9cc8e31f

I don't want to mess around with it, without knowing what happened to the page. Maybe someone might have a look, that is more involved into the topic? Is this by accident? Or an attack? (The account, who did the change does not look very serious). Or did I overlook something?

**Comment by Lersoo** [comment]
I have restored the wiki page to its original state as it seemed still relevant. I also added the default value of `after_sign_out_path_for`.

Nice catch ! 👍🏼

**Comment by prithvi16** [comment]
I just checked, anyone can edit wiki pages without committer provolages. Is this on purpose?

**Comment by carlosantoniodasilva** [comment]
@prithvi16 it is, or at least it has always been like that as far as I remember. That being said, I have been considering closing it and working on those wiki guides more "officially" at some point.

Thanks for restoring that one @Lersoo.
