### ISSUE TITLE
Wrong Response when Unauthorized

### ISSUE THREAD

**Issue by CarlosUvaSilva** [heartcombo/devise#5344]
## Environment

- Ruby 3.0.0
- Rails 6.1.1
- Devise 4.7.3
- Devise-jwt 0.8.0

## Current behavior

When I pass the wrong password or the wrong root object (in this case "admin") the API return a 200 with the admin info as null and it's redirecting the request to the new controller

![image](https://user-images.githubusercontent.com/6827956/107128547-70c18780-68b6-11eb-9442-19d14ff28aec.png)
![image](https://user-images.githubusercontent.com/6827956/107128554-82a32a80-68b6-11eb-894d-3bb7eba3e633.png)

## Expected behavior

API should not redirect to sessions#new and just return 401. 
I have the same code in more than one project (different versions) and they all work as expected just not this one

![image](https://user-images.githubusercontent.com/6827956/107128591-cf870100-68b6-11eb-8267-506e0d6622b9.png)

**Comment by carlosantoniodasilva** [comment]
It looks like your request is being processed as HTML and so a redirect is probably happening as the default behavior. You might need to set the proper format for the request if you're sending JSON & expecting JSON back.

If that is not the case, I'd ask for you to double check what configurations you may have customized in your devise initializer, or if you have a custom failure app as well. If nothing stands out, please share those so we can have more context.

**Comment by CarlosUvaSilva** [comment]
@carlosantoniodasilva I just updated another project to latest Ruby/Rails/Devise and this is happening again :cry: 
did any default config changed that I am missing?

**Comment by carlosantoniodasilva** [comment]
@CarlosUvaSilva updated from which versions to which versions? I can't think of anything that could have changed on Devise's side of things... also, does this _only_ happen with Devise involved?

**Comment by PedroAugustoRamalhoDuarte** [comment]
@CarlosUvaSilva could be the cache from session, check this instructions in devise-jwt: https://github.com/waiting-for-dev/devise-jwt#session-storage-caveat

**Comment by chrisgeek** [comment]
I faced same issue, specifying the route as `default: {format: json}` was the solution for me. @carlosantoniodasilva was right, has to do with the response format.

**Comment by carlosantoniodasilva** [comment]
Thanks for reporting. I'm closing based on this being related to the request/response format, please report back if you have more info that says otherwise.
