### ISSUE TITLE
page does not consistently redirect, on login/logout using Turbo-Rails with Devise 4.7.3 (known issue) -- 

### ISSUE THREAD

**Issue by jasonfb** [heartcombo/devise#5358]
- Ruby **2.6.3**
- Rails **6.1.3**
- Devise **4.7.3**
- Turbo-Rails **0.5.9**

REPRODUCTION APP CODE: https://github.com/jasonfb/TR002

Symptom: When I click Log In, the browser window hangs even though the backend processes the Log in action & also appears to process the redirect, but does not update the browser window

![TR002 — fsevent_watch ◂ localhost:3000)  TR002  NVM_INC=:Users:jason: nvm:versions:node:v12 8 0:include:node rvm_bin_path=:User… 2021-03-13 15-08-25](https://user-images.githubusercontent.com/59002/111043227-6d6a7000-840f-11eb-950a-f4b425e64295.png)

Please note this is cross-posted to turbo-rails here 
https://github.com/hotwired/turbo-rails/issues/122

you can reproduce fully on your own machine using these steps https://gist.github.com/jasonfb/eb9cf8e90514dad1af0b98e01e9bce3d

-----------
# 
This seems like it is a **known-issue** and has been fixed in this PR 
https://github.com/heartcombo/devise/pull/5340

I searched closed & open devise issues and found nothing with "turbo" in the title of the issue so I am leaving this here mostly for search engines even though it looks like the PR above is the resolution. 

Update 2021-03-13@11-45EST: I found this PR that appears to be from Jan 6 which looks like (?) the root cause
https://github.com/heartcombo/devise/pull/5325

Note: I did not test against devise master, should I?

----------

**Symptom 1**:  
-- using Turbo-Rails + Devise 

When I click "Log In", the form submits but the page does not reload.

Step 1: go to 

/users/sign_in

Enter a good username & password (you can sign up or make one on the command line)

[![enter image description here][1]][1]

Click "Sign In"

[![enter image description here][2]][2]

on the back end the request WAS processed and even redirected, but the redirect did not happen on the front end. You (the user) **_ARE_** actually logged in even though your page is hanging and did not redirect to the root path

[![enter image description here][3]][3]

Result: Page hangs.
Expected result: Turbo Rails redirects correctly to the new page

----------
**Symptom 2**

When I click "Log Out", the page does nothing. 
on the backend I am actually logged out, but the page does not change.
If I reload, I see that I am now logged out

Step 1: be logged in

Step 2: Click to "log out"
[![enter image description here][4]][4]

Notice that the button stays 'grey' (clicked), the request is processed on the back end:

[![enter image description here][5]][5]

Result: Page hangs

Expected result: Turbo Rails redirects correctly to the new page

The user IS ACTUALLY logged out, but the page hangs and does not redirect. (if the user reloads their page they find that they are in fact logged out now.)

  [1]: https://i.stack.imgur.com/4Ug3D.png
  [2]: https://i.stack.imgur.com/XVtCs.png
  [3]: https://i.stack.imgur.com/LXwZX.png
  [4]: https://i.stack.imgur.com/IChpW.png
  [5]: https://i.stack.imgur.com/pVZJP.png

**Comment by jasonfb** [comment]
TEMPORARY FIX:

- overrride the devise form (use `rails generate devise:views` to generate custom views)

- then you will edit the registrations/new and sessions/new modifying both like so:

- `form_for(resource, as: resource_name,   url: session_path(resource_name) ) do |f|`
- change it to `form_for(resource, as: resource_name,  **html: {'data-turbo' => "false"},** url: session_path(resource_name) ) do |f|`

this tells Devise to fall back to non-Turbo interaction for the log-in and registration. 

- For your **_Logout_** links use Rails `button_to` instead of `link_to` and the symptom goes away.


note: recommend as a temporary fix until the root cause is addressed

**Comment by ngelx** [comment]
I've had to add `data-turbo: false` to the `button_to`

```ruby
<%= button_to destroy_user_session_path, method: :delete, form: { "data-turbo" => "false" } do %>
    <i class="zmdi zmdi-power"></i>Logout
<% end %>
```

**Comment by MihaiVoinea** [comment]
I have problems with Turbo-Rails on sign up as well.

After a new account signs up, the redirect fails and I get 
`undefined method 'user_url' for #<Devise::RegistrationsController:0x0000000000c058>`.
Here is the full trace: 
```
actionpack (6.1.3) lib/action_dispatch/routing/polymorphic_routes.rb:231:in `public_send'
actionpack (6.1.3) lib/action_dispatch/routing/polymorphic_routes.rb:231:in `polymorphic_method'
actionpack (6.1.3) lib/action_dispatch/routing/polymorphic_routes.rb:116:in `polymorphic_url'
actionpack (6.1.3) lib/action_dispatch/routing/url_for.rb:188:in `full_url_for'
actionpack (6.1.3) lib/action_dispatch/routing/url_for.rb:171:in `url_for'
actionpack (6.1.3) lib/action_controller/metal/redirecting.rb:110:in `_compute_redirect_to_location'
actionpack (6.1.3) lib/action_controller/metal/redirecting.rb:63:in `redirect_to'
actionpack (6.1.3) lib/action_controller/metal/flash.rb:58:in `redirect_to'
actionpack (6.1.3) lib/action_controller/metal/instrumentation.rb:66:in `block in redirect_to'
activesupport (6.1.3) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.3) lib/active_support/notifications.rb:203:in `instrument'
actionpack (6.1.3) lib/action_controller/metal/instrumentation.rb:65:in `redirect_to'
responders (3.0.1) lib/action_controller/responder.rb:147:in `redirect_to'
responders (3.0.1) lib/action_controller/responder.rb:207:in `navigation_behavior'
responders (3.0.1) lib/action_controller/responder.rb:174:in `rescue in to_html'
responders (3.0.1) lib/action_controller/responder.rb:171:in `to_html'
responders (3.0.1) lib/action_controller/responder.rb:165:in `respond'
responders (3.0.1) lib/action_controller/responder.rb:158:in `call'
responders (3.0.1) lib/action_controller/respond_with.rb:213:in `respond_with'
devise (4.7.3) app/controllers/devise/registrations_controller.rb:25:in `create'
actionpack (6.1.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.1.3) lib/abstract_controller/base.rb:228:in `process_action'
actionpack (6.1.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.1.3) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.1.3) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
actiontext (6.1.3) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (6.1.3) lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
activesupport (6.1.3) lib/active_support/callbacks.rb:126:in `instance_exec'
activesupport (6.1.3) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
activesupport (6.1.3) lib/active_support/callbacks.rb:137:in `run_callbacks'
actionpack (6.1.3) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.1.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.1.3) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (6.1.3) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.3) lib/active_support/notifications.rb:203:in `instrument'
actionpack (6.1.3) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
actionpack (6.1.3) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
activerecord (6.1.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.1.3) lib/abstract_controller/base.rb:165:in `process'
actionview (6.1.3) lib/action_view/rendering.rb:39:in `process'
actionpack (6.1.3) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.1.3) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.1.3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.1.3) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.1.3) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.1.3) lib/action_dispatch/routing/mapper.rb:49:in `serve'
actionpack (6.1.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (6.1.3) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.3) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.3) lib/action_dispatch/routing/route_set.rb:842:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.1.3) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (6.1.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (6.1.3) lib/active_record/migration.rb:601:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.3) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.3) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.3) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.3) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.3) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.3) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.3) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
railties (6.1.3) lib/rails/engine.rb:539:in `call'
puma (5.2.2) lib/puma/configuration.rb:248:in `call'
puma (5.2.2) lib/puma/request.rb:76:in `block in handle_request'
puma (5.2.2) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
puma (5.2.2) lib/puma/request.rb:75:in `handle_request'
puma (5.2.2) lib/puma/server.rb:431:in `process_client'
puma (5.2.2) lib/puma/thread_pool.rb:145:in `block in spawn_thread' 
```
Using `"data-turbo" => "false"` fixes this for me.

**Comment by jasonfb** [comment]
supposedly this may be fixed in Devise on master (have not tested), this bug only to report on **Devise 4.7.3** because it is the latest (as of when I filed the bug)

**Comment by asnCode** [comment]
Exactly same bug in a rails 6 with devise 4.8.0, need to add form: { "data-turbo" => "false" } ....

**Comment by jeygeethan** [comment]
Are there any plans to fix this for Rails 7? Do let me know If I can help in someway.

**Comment by carlosantoniodasilva** [comment]
@jeygeethan there's some in the works, for now we recommend disabling turbo on these links until we get a new version fully compatible out there. Thanks.
