### ISSUE TITLE
When adding Devise to an application with an existing User making the mistake of forgetting to run the installer, it seems to bork the application, database can't migration and devise routes aren't available

### ISSUE THREAD

**Issue by jasonfb** [heartcombo/devise#5359]
## Environment

Ruby **2.6.3**
Rails **6.1.3**
Devise **4.7.3**

## example app
https://github.com/jasonfb/DEVISE002

## steps to reproduce
1- `rails new TestApp`
2- `cd TestApp/`
3- add `gem devise` to Gemfile & bundle install
4- Now,  create a User model (as if you had a User model existing before you added Devise to your app) , do this with `rails generate model User`

5- now *make the mistake* of forgetting to run the devise installer itself

6- now run the devise generator on your already-created User with `rails generate devise User`

7- run `rails db:migrate`. this migration will FAIL, throwing the following error:

(does not make sense, because devise is installed into the gem file)

```
jason@MBP ~/Work/_LEARNING/Turbo-Rails/DEVISE002 (master) $ rails db:migrate
rails aborted!
NoMethodError: undefined method `devise' for User (call 'User.connection' to establish a connection):Class
/Users/jason/Work/_LEARNING/Turbo-Rails/DEVISE002/app/models/user.rb:4:in `<class:User>'
/Users/jason/Work/_LEARNING/Turbo-Rails/DEVISE002/app/models/user.rb:1:in `<main>'
/Users/jason/Work/_LEARNING/Turbo-Rails/DEVISE002/config/routes.rb:2:in `block in <main>'
/Users/jason/Work/_LEARNING/Turbo-Rails/DEVISE002/config/routes.rb:1:in `<main>'
/Users/jason/Work/_LEARNING/Turbo-Rails/DEVISE002/config/environment.rb:5:in `<main>'
/Users/jason/Work/_LEARNING/Turbo-Rails/DEVISE002/bin/rails:5:in `<top (required)>'
/Users/jason/Work/_LEARNING/Turbo-Rails/DEVISE002/bin/spring:10:in `block in <top (required)>'
/Users/jason/Work/_LEARNING/Turbo-Rails/DEVISE002/bin/spring:7:in `tap'
/Users/jason/Work/_LEARNING/Turbo-Rails/DEVISE002/bin/spring:7:in `<top (required)>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)

```

### mistake
this happens explicitly when you add devise to an app with an already existing  User and you forget to run `rails generate devise:install`

TO FIX: run `rails generate devise:install`

## Current behavior

Symptom 1: The database doesn't migrate and `rails db:migrate` crashes with the above error. 

Symptom 2: on one of my test apps where I made this mistake, the devise routes didn't seem to load although `devise_for :users` was in the routes.rb file. 

## Expected behavior

- maybe just an error message telling me that I accidentally generated Devise onto my User but forgot to run the installer correctly with `rails generate devise:install`

**Comment by carlosantoniodasilva** [comment]
I'm unable to test this now, but at a glance I'm guessing it's not something devise specific, it seems like it could be `spring`, and calling `spring stop` to stop the server should work.

Spring usually doesn't play nice with adding new gems.

**Comment by jasonfb** [comment]
@carlosantoniodasilva -- it's a mistake, it's my mistake I've figured it out will close in a minute.
