### ISSUE TITLE
Compatibility with Rails 7 (breaking change in dependency management with Zeitwerk)

### ISSUE THREAD

**Issue by jlecour** [heartcombo/devise#5365]
## Environment

- Ruby **3.0.0**
- Rails **7.0.0-alpha** (after 14d4edd7c3b06e82e1fcef54fa0b4453315c35fd)
- Devise **4.7.3**

## Current behavior

The Rails application doesn't boot anymore, with this error : `undefined method 'reference' for ActiveSupport::Dependencies:Module`

The method has been removed and Devise has to change its integration with Rails.

I've reported this in the Rails Issue tracker : https://github.com/rails/rails/issues/41706

**Comment by jlecour** [comment]
Duplicate of #5357. Sorry!

**Comment by carlosantoniodasilva** [comment]
Thanks @jlecour.
