### ISSUE TITLE
Filter chain halted as :check_captcha rendered or redirected

### ISSUE THREAD

**Issue by sbryans** [heartcombo/devise#5367]
The /users/sign_in page works swimmingly with captcha integration. The /users/sign_up page, however, does not.
I've followed the guide @ `https://github.com/heartcombo/devise/wiki/How-To:-Use-Recaptcha-with-Devise` to the letter.

## Environment

- Ruby **[2.6.3]**
- Rails **[6.0.3.4]**
- Devise **[4.7.3]**

## Current behavior

Filter chain halted as :check_captcha rendered or redirected.
Captcha never passes.

## Expected behavior

Captcha should pass when entered correctly.

**Comment by schepens83** [comment]
I seem to have the same issue. similar rails and devise version. ruby 2.5.1
Also followed the guide and also in sign_up.

**Comment by schepens83** [comment]
Okay. I think actually the guide is wrong. In
`return if !verify_recaptcha(action: 'signup') `
It seems to skip the rest of the method if recaptcha fails instead of succeeds. Removing the ! fixed the problem for me.

**Comment by carlosantoniodasilva** [comment]
That seems to make sense @schepens83. I have never used recaptcha with Devise in that way but I can try to build up a test app and review the wiki to see what's misguided there.

@sbryans you mention sign in works but sign up doesn't, have you noticed any difference between the two? The wiki example has the same "issue" above on all of them it seems, but maybe you coded sign in vs up differently?

**Comment by sbryans** [comment]
In my **sessions_controller.rb** override for Devise.

`prepend_before_action :check_captcha, only: [:create]`
...
`def check_captcha
    unless verify_recaptcha
      self.resource = resource_class.new sign_in_params
      respond_with_navigational(resource) { render :new }
    end
 end`
...

The registrations_controller.rb is similar, yet only the sessions controller seems to work. I'm sure it's a simple configuration issue on my part.

**Comment by CertifiedRascal** [comment]
@schepens83 Yeah, I needed to do this for "sign in" form after following the guide also. It seems that maybe the logic was reversed in the recaptcha gem? Either way, deleting the exclamation mark worked for me.

**Comment by firecall** [comment]
Just confirming, the docs are backwards! :-)

`return if verify_recaptcha`

Is the correct statement!

Otherwise you get in a loop back to the login page, and not completing the capture will log you in OK!

**Comment by mices** [comment]
I have the same problem   
prepend_before_action :check_captcha, only: [:new, :create]

**Comment by nashby** [comment]
Looks like Wiki was updated so I'm closing this.
