### ISSUE TITLE
Devise is marking email addresses generated by the Faker gem as invalid

### ISSUE THREAD

**Issue by arimendelow** [heartcombo/devise#5371]
## Pre-check

I've been experiencing this issue for well over a year now, and periodically search the internet but to no avail.

Using the RSpec and Faker gems along with factory bot (6.1.0), I am generating test users. Often, the user will fail validations with "email is invalid".

## Environment

- Ruby **2.7.1**
- Rails **6.0.3**
- Devise **4.7.2**

## Current behavior

Here is my user factory:

```ruby
FactoryBot.define do
  factory :user do
    first_name { Faker::Name.first_name }
    last_name { Faker::Name.last_name }
    username { Faker::Internet.username(specifier: 2, separators: %w[]) } # minimum 2 letters and only letters
    email {  Faker::Internet.email }
    password { 'Test1234!!' }
    password_confirmation { 'Test1234!!' }

    trait :customer do
      role { :customer }
    end

    trait :admin do
      role { :admin }
    end
  end
end
```

I expect this to always pass validation. Instead, I often get the following (not specifically with this spec, but for example):

```
Failure/Error: user { create(:user) }
     
     ActiveRecord::RecordInvalid:
       Validation failed: Email is invalid
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/evaluation.rb:18:in `create'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/strategy/create.rb:12:in `block in result'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/strategy/create.rb:9:in `tap'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/strategy/create.rb:9:in `result'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/factory.rb:43:in `run'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/factory_runner.rb:29:in `block in run'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/factory_runner.rb:28:in `run'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/strategy_syntax_method_registrar.rb:28:in `block in define_singular_strategy_method'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/evaluator.rb:43:in `method_missing'
     # ./spec/factories/comments.rb:5:in `block (3 levels) in <top (required)>'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/attribute/dynamic.rb:16:in `instance_exec'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/attribute/dynamic.rb:16:in `block in to_proc'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/evaluator.rb:85:in `instance_exec'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/evaluator.rb:85:in `block in define_attribute'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/attribute_assigner.rb:58:in `get'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/attribute_assigner.rb:16:in `block (2 levels) in object'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/attribute_assigner.rb:15:in `each'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/attribute_assigner.rb:15:in `block in object'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/attribute_assigner.rb:14:in `tap'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/attribute_assigner.rb:14:in `object'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/evaluation.rb:13:in `object'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/strategy/create.rb:9:in `result'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/factory.rb:43:in `run'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/factory_runner.rb:29:in `block in run'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/factory_runner.rb:28:in `run'
     # /Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/factory_bot-6.1.0/lib/factory_bot/strategy_syntax_method_registrar.rb:28:in `block in define_singular_strategy_method'
     # ./spec/models/comment_spec.rb:12:in `block (2 levels) in <top (required)>'
```

## Expected behavior

I expect to not have this error.

**Comment by carlosantoniodasilva** [comment]
Do you have a custom `email_regexp` set on Devise?

I'm unable to repro this with a few tries of this small script: (using `faker (2.17.0)`, `devise (4.7.3)`)

```
% ruby -r faker -r devise -e "puts 1000.times.map { Faker::Internet.email }.reject { |e| Devise.email_regexp.match? e }.inspect"
[]
```

**Comment by arimendelow** [comment]
I don't, and I also never get this error with my seedfile (though that's creating many less users) - is it possible the error is with FactoryBot or RSpec?

**Comment by carlosantoniodasilva** [comment]
Devise's default email regex is very simple and just aimed to avoid basic/common mistakes with emails. It also seems unlikely to be FactoryBot or RSpec in this case.

It sounds like that is something that may happen randomly at times with Faker? Are you able to add some logging that can at least output the email that's being tested with that fails, so we could reproduce it?

I don't think the email regex in Devise will change necessarily any time soon, but a way to see the email and repro it would be nice.

You might also want to try comparing those same emails with `URI::MailTo::EMAIL_REGEXP` which is a much more sophisticated regex, just to see if the same emails generated by Faker would match there.

**Comment by arimendelow** [comment]
There's no way to log that I know of - I've opened up [an issue](https://github.com/thoughtbot/factory_bot/issues/1484) on the FactoryBot gem that will hopefully help shine some light.

**Comment by carlosantoniodasilva** [comment]
Maybe instead of `create` a user, you `build` it, check for its validity, and output the user email if it doesn't validate or something like that?

Also please share your `Devise.email_regexp`, and if you have any other validations on the `email` field on your model.

Without any way to reproduce it or see some output / details of what could be causing the issue, I'm not gonna be able to offer much

**Comment by arimendelow** [comment]
Aha! Here's an example of an email that fails the regex: "nu@schimmel.com"

I see now from looking at the regex that it'll fail any email addresses with less than 3 letters before the @. While rare, it's not impossible - [see here for one crazy example](https://www.theverge.com/2020/6/16/21293156/hey-email-service-2-letter-addresses-premium-price-features).

Is this intentionally unsupported?

**Comment by carlosantoniodasilva** [comment]
@arimendelow cool, that's good info.

I'm not sure where you see it will fail email address with < 3 chars in the username part? Is that configured on your app, perhaps in config/initializers/devise.rb?

Here's the current regex in Devise master: https://github.com/heartcombo/devise/blob/5d5636f03ac19e8188d99c044d4b5e90124313af/lib/devise.rb#L116

Testing it against the email you shared with 2 letters:

```ruby
irb> Devise.email_regexp
=> /\A[^@\s]+@[^@\s]+\z/
irb> Devise.email_regexp.match? 'nu@schimmel.com'
=> true
```

We even have a test with email `jo@jo.co` as a valid email: https://github.com/heartcombo/devise/blob/5d5636f03ac19e8188d99c044d4b5e90124313af/test/devise_test.rb#L98-L99

**Comment by arimendelow** [comment]
Yup, look at that. I'm using the following custom regex -
```ruby
  /             start of regex
  \A            match start of string
  \w+           at least one word character
  [\w+\-.]+     at least one word character, plus a hyphen or dot
  \w+           at least one word character
  @             exactly one literal at sign
  [a-z\d]+      at least one letter or digit
  [a-z\d\-.]+   at least one letter, digit, hyphen, or dot
  [a-z\d]+      at least one letter or digit
  \.            exactly one literal dot
  [a-z]{2,}     at least two letters
  \z            match end of string
  /             end of regex
  i             case insensitive
```

Now that I see it, it's coming back to me. This is an older project that I had migrated over to Devise and kept the regex, I completely forgot about it :) Thanks for all the help! Will close this issue.

And thanks for all the work you do on Devise, by the way. Absolute gem of a gem.

**Comment by carlosantoniodasilva** [comment]
Cool, mystery solved :). Thanks!
