### ISSUE TITLE
warden_message no longer available to failure app

### ISSUE THREAD

**Issue by chadwilken** [heartcombo/devise#5374]
## Environment

- Ruby **2.6.6**
- Rails **6.0.3.6**
- Devise **4.7.1**

## Current behavior
We have a custom failure app where we return a value based on the message passed to `fail`. We upgraded from version **4.6.2** where this had been working. We didn't notice until recently that it had broken.

Failure App:
```ruby
module Devise
  class CustomFailure < Devise::FailureApp
    def respond
      if request_format == :json
        json_error_response
      else
        super
      end
    end

    def json_error_response
      self.headers['WWW-Authenticate'] = 'Bearer realm=Application'
      self.status = 401
      self.content_type = request.format.to_s
      self.response_body = [
        {
          error: { general: message, type: warden_message },
          messages: [message]
        }
      ].to_json
    end

    def message
      case warden_message
      when :device_limit
        'This account has been logged out because you are over your device limit for this user account.'
      when :force_logout
        'This account has been logged out because you have been forced to do so.'
      when :password_reset
        'This account has been logged out because your password was reset.'
      else
        'Bad credentials.'
      end
    end
  end
end
```

We have a custom `TokenAuthenticatable` strategy. I've simplified it a bit but you get the gist.

```ruby
# token_authenticatable.rb

# frozen_string_literal: true

module Devise
  module Strategies
    class TokenAuthenticatable < Authenticatable

      attr_accessor :auth_token

      def valid?
        (valid_for_params_auth? || valid_for_http_auth?) && credentials.present?
      end

      def authenticate!
        env['devise.skip_trackable'] = true

        token = AuthToken.find_by(encrypted_token: credentials)
        
        return fail!(:invalid) unless token.present?
        # An example reason is :force_logout
        return fail!(token.deleted_reason.to_sym) if token.discarded?

        resource = mapping.to.find_by(id: token.user_id)

        if validate(resource)
          success!(resource)
        else
          fail(:invalid)
        end
      end

      def store?
        false
      end

      def clean_up_csrf?
        false
      end

      private

        def valid_for_params_auth?
          params_authenticatable? && valid_params?
        end

        def valid_for_http_auth?
          self.authentication_type = :http_auth
          request.authorization.present? && credentials.present?
        end


        def credentials
          if request.authorization.present?
            token, options = ActionController::HttpAuthentication::Token.token_and_options(request)
            token
          elsif params[:auth_token].present?
            params[:auth_token]
          end
        end

        def valid_params?
          params[:auth_token].present?
        end
    end
  end
end

Warden::Strategies.add(:token_authenticatable, Devise::Strategies::TokenAuthenticatable)
Devise.add_module(:token_authenticatable, strategy: :token_authenticatable)
```

```ruby
# devise.rb initializer

require 'devise/custom_failure'
require 'devise/models/token_authenticatable'
require 'devise/strategies/token_authenticatable'

# Use this hook to configure devise mailer, warden hooks and so forth.
# Many of these configuration options can be set straight in your model.

Devise.add_module(:token_authenticatable, strategy: true, no_input: true)

Devise.setup do |config|
  config.mailer.class_eval do
    helper :subdomain
  end

  config.warden do |manager|
    manager.failure_app = Devise::CustomFailure
  end

  ActiveSupport.on_load(:devise_failure_app) do
    include Turbolinks::Controller
  end
end
```

This all works just fine as long as auth is successful but if it isn't successful then I get the default value `Bad Credentials` from the failure app above.

## Expected behavior

I have access to the value of `warden_message` in the failure app so that I can construct a custom error message. Perhaps we're abusing the `warden_message` and there is a supported way of achieving what we are doing.

**Comment by chadwilken** [comment]
I'm going to close this. Even though the behavior changed I am able to stash it in the `env` and retrieve it in the failure app.

**Comment by carlosantoniodasilva** [comment]
Thanks @chadwilken.

I don't see anything in the [changelog](https://github.com/heartcombo/devise/blob/master/CHANGELOG.md#471---2019-09-06) or the [code](https://github.com/heartcombo/devise/compare/v4.6.2...v4.7.1) that would explain the behavior you're describing/expecting changed.

Might be worth checking if anything else changed there. (e.g. warden, another dependency, etc) Hope that helps.

**Comment by masciugo** [comment]
Hi,
I am using 4.9.2 and I am experiencing the same issue. `warden_message` is nil in my custom failure app even if I call `fail(:my_error_message)` in my custom strategy authenticate! method.

@chadwilken could please better elaborate your solution?

thank you

**Comment by chadwilken** [comment]
> Hi, I am using 4.9.2 and I am experiencing the same issue. `warden_message` is nil in my custom failure app even if I call `fail(:my_error_message)` in my custom strategy authenticate! method.
> 
> @chadwilken could please better elaborate your solution?
> 
> thank you

Before we call `fail` in our custom strategy we do `env['devise.token.deleted_reason'] = 'Your message here'`. Then in `CustomFailure` we use that key to find the correct message using `I18n`.
