### ISSUE TITLE
ORM Dependency causing errors while implementing with sequel-rails

### ISSUE THREAD

**Issue by mofmn** [heartcombo/devise#5377]
## Environment

- Ruby **2.7.1**
- Rails **6.0.3.3**
- Devise **4.8.0**

## Current behavior

When trying to reset a password this error is produced after using the link with the token. it seems like it is expecting reset_password_sent_at to be a Date object but it is a string. This is running on a recent install of devise - i am using sequel ORM rather than active record but i don't think that should affect anything controller side.

![image](https://user-images.githubusercontent.com/9949335/116775695-52c38780-aa9f-11eb-8c35-46674de0ba8a.png)

**Comment by mofmn** [comment]
So my initial impression was that it would get the variable through the controller, and i was of course wrong, its getting it through the model so i added this to my User model

`
def reset_password_sent_at
    Time.parse(super)
  end
`

And that allowed it to pass this error , however, immediately ran into another, which i am going to guess is another ORM issue. 

![image](https://user-images.githubusercontent.com/9949335/116779519-93c49780-aab1-11eb-8c2b-ebde20a95477.png)


I had already installed sequel devise hoping to deal with these issues but that obviously hasn't been much good, (neither was the sequel devise generator). 

Is it sensible if i document these as i progress through them, then perhaps changes could be made to make Devise more independent of the ORM?

**Comment by mofmn** [comment]
So I was being a derp for a while, but i fixed this in the end by putting this method in my model class ( my model extends Sequel::Model, which is where the incompatibility comes from )
`
 def reset_password_sent_at
    if super
       Time.parse(super)
    end
  end
  `
  
  It seems like this is because Devise is expecting to receive Date objects from the ORM/model and sequel is only providing literal values of the database. It seems possible that some convention isn't being followed that would maintain Devise as independent from the choice of ORM, Perhaps Sequel isn't following these conventions, but it tends to be a pretty strict on rules in general, which is why it's good.

**Comment by carlosantoniodasilva** [comment]
Devise is meant to be mostly ORM independent, in fact it used to work just fine with both Active Record and Mongoid ORMs (more recently it's stopped testing against mongoid due to some issues and it was never added back, that's on my list, but it still strives to be compliant with both)

Regards to your issue, I'm not interested in adding any type of parsing to Devise itself, I believe that's the ORM's job. It does sound like that particular column/field is set to be a string and not a date/datetime column, maybe in your database? I'm wondering if it's just Sequel reflecting that it is a string and not doing any parsing work for you.

I've never tested with Sequel myself and so I can't offer much help there honestly. Are you using another library to make any bridge necessary? I'm happy to adjust things on Devise's end if that ends up being needed, but it does seem like an ORM thing from the looks of it.

**Comment by mofmn** [comment]
Ok so it appears i was still being a bit dumb (not uncommon), I used a generator from sequel devise generators to set up the migration, and it produced something that was probably more of an AR migration so i had to morph what it produced into a sequel migration, which i did without checking the sanity of the datatypes, and it had put reset_password_sent_at as a string so good call on that one ( sorry for not checking the obvious ). 

Unfortunately there is still an issue. So as far as i can tell reset_password_sent_at is set here - 
`
        def set_reset_password_token
          raw, enc = Devise.token_generator.generate(self.class, :reset_password_token)

          self.reset_password_token   = enc
          self.reset_password_sent_at = Time.now.utc
          save(validate: false)
          raw
        end
`

Which is converting the time to UTC and then sending it to the ORM. Unfortunately Sequel stores the timezone with the datetime so as i am in UTC + 9  this effectively steps the time back 9 hours, meaning that a 6 hour window is not enough. 

So it appears that Sequel is missing the UTC identifier when storing the time, and i am not sure how to correct this at the moment. I don't know whether the error is more sequels issue than devise, i am reluctant to point any fingers, it looks like sequel, but sequels got a habit of being correct in a lot of situations like this. I am going to keep investigating. If you are aware of a way to deal with this please let me know (even if its just a workaround), otherwise i will let you know what i find.

**Comment by mofmn** [comment]
After some investigation, i found the resolution to this - Sequel supports databases that do not store timezones and so has a variety of ways of dealing with them. The most direct solution was to load the extension named timezones in application.rb -

        module RailsApp
          class Application < Rails::Application
            config.sequel.after_connect = proc do
              Sequel.extension :named_timezones
            end
          end
        end
        
Once i have done testing, would you like me to list the necessary adjustments to allow Sequel to interface with Devise in rails so they can be documented?

**Comment by carlosantoniodasilva** [comment]
Devise does it best so always use UTC in these timestamp columns, and it leaves up to the ORM to handle any TZ changes if it should store things in a different TZ. I know that AR should handle it okay, I'm not sure about Sequel, but it sounds like that extension you found is the way to go.

If there's any adjustment necessary on Devise to work better with Sequel and keep compatibility with other ORMs, I'm happy to help work through those. For now I'm not sure there's anything Devise needs to do here though.

If you have any suggestions please feel free to send them here or if even a PR. In the meantime I'll go ahead and close the issue, as the original report seems to be specific to your app + Sequel. Thanks!
