### ISSUE TITLE
programmatically sign_in user and redirect_to raise 401 Unauthorized

### ISSUE THREAD

**Issue by axcr** [heartcombo/devise#5390]
## Environment

- Ruby 3.0.1p64
- Rails 6.1.4
- Devise 4.8.0

## Current behavior
Programmatically sign_in user and redirect_to target with before_action :authenticate_user! raise 401 unauthorized exception and redirect_to target defined for failed login attempts.

I'm sure user is correct assigned and sign_in works at the moment before redirect start, but then logs shows following redirect chain:

`
Processing by Users::BookingsController#canceled as HTML
sign_in #<User id: 203, email: "test@test.com", created_at: "2021-06-20 11:08:15.086186000 +0000", updated_at: "2021-06-20 11:08:15.086186000 +0000">
Redirected to http://localhost:3000/account/booking/108
Completed 302 Found in 264ms (ActiveRecord: 1.1ms | Allocations: 4898)
Started GET "/account/booking/108" for ::1 at 2021-07-05 16:59:55 +0200
Processing by Users::BookingsController#show as HTML
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms | Allocations: 274)
Started GET "/account/login" for ::1 at 2021-07-05 16:59:55 +0200
`
## Expected behavior
sign_in user and redirect_to target should work and user should be signed_in and authenticate_user should works too.

## Configuration
My app using redis for user sessions storage.
Rails.application.config.session_store :cache_store, key: '_session', compress: true, pool_size: 5, same_site: :strict, secure: Rails.env.production?

## Update
It seems that same_site: :strict in Rails.application.config.session_store :cache_store is the candidate why it raised 401 unauthorized. Is this the expected behaviour ?

**Comment by carlosantoniodasilva** [comment]
I don't see anything on Devise that could cause this, but it does seem like redirects and cookie SameSite=Strict could be the cause since it's possible the cookies aren't being sent via that redirect, if the browser is somehow not considering it SameSite. Have you tried with Lax?

**Comment by Hanaffi** [comment]
@carlosantoniodasilva I tried with `:none` but doesnt work too , any thoughts?

**Comment by carlosantoniodasilva** [comment]
@Hanaffi nothing comes to mind honestly, never had this issue... if you can reproduce in a sample app, assuming that it only happens with Devise, we can try to take a look.

**Comment by Michoels** [comment]
I recently ran into a similar issue with SameSite `strict` cookies.
I found that setting `config.action_dispatch.cookies_same_site_protection = :strict` broke login with Omniauth.
(I'm using the [omniauth-azure-activedirectory-v2](https://github.com/RIPAGlobal/omniauth-azure-activedirectory-v2) plugin)

Changing the cookie setting to `:lax` solved the problem, but I'm not sure why.
