### ISSUE TITLE
Instructions on needing to move views no longer relevant?

### ISSUE THREAD

**Issue by jjb** [heartcombo/devise#5391]
this section: https://github.com/heartcombo/devise#configuring-controllers says

> Since the controller was changed, it won't use the default views located in devise/sessions

I found this to not be the case in my project. I have customized controllers and did not need to move the views. maybe smarter view detection was implemented at some point and the readme wasn't updated? if that's the case i'll submit a PR with a readme update.

![CleanShot 2021-07-17 at 13 24 25@2x](https://user-images.githubusercontent.com/6097/126036770-6fadbc0f-f677-4960-a48e-fa0c8664c1cd.png)

![CleanShot 2021-07-17 at 13 26 15@2x](https://user-images.githubusercontent.com/6097/126036809-685bf34d-5edb-4720-aed0-03db30f55546.png)

*routes*

```ruby
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
```

**Comment by carlosantoniodasilva** [comment]
I have updated this in 41e2db212065f2a75a5d73e76d6eb8ecd53a6acf, related to #5526, but I missed this issue. It is indeed not necessary to move the views, I hope the new copy makes that a bit clearer. Thanks!
