### ISSUE TITLE
Safari - Omniauth - Empty session after #sign_in_and_redirect call

### ISSUE THREAD

**Issue by julienpierlot** [heartcombo/devise#5404]
## Environment

- Ruby 2.7.1
- Rails 6.1.4
- Devise 4.8.0

On `localhost:3000`

## Current behavior
When trying to sign in through Google Oauth 2 using the Safari browser, once the method #sign_in_and_redirect, I am redirected to the after sign in page, but I am not logged in. And when I inspect the session object, here is what I have:
`#<ActionDispatch::Request::Session:0x24c98 not yet loaded>`.

Everything works fine on Google Chrome.

## Expected behavior
I should be signed in after redirect.

## My setup
Implemented omniauthable for model `User`
config in `config/initializers/device.rb`:
```ruby
  config.omniauth :google_oauth2, omniauth_config[:google][:client_id], omniauth_config[:google][:client_secret], provider_ignores_state: true
```
FYI if I remove the option key `provider_ignores_state: true`,  an error is raise by the omniauth gem `Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected`, only on Safari browser (it works fine on  Google Chrome).

content of my controller file `app/controllers/users/omniauth_callbacks_controller.rb`:
```ruby
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_oauth2_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_session_path
    end
  end

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_session_path
    end
  end

  def failure
    redirect_to new_user_session_path
  end
end
```

Regarding session, I have an initializer in `config/initializers/session_store.rb`:
```ruby
MyApp::Application.config.session_store :cookie_store, key: '_app'
```

In `config/application.rb`, I tried setting `no-store` and `no-cache` headers (following this https://blog.alex-miller.co/rails/2017/01/07/rails-authenticity-token-and-mobile-safari.html), but it did not change anything:
```ruby
    config.action_dispatch.default_headers.merge!(
      'Cache-Control' => 'no-store, no-cache'
    )
```

**Comment by julienpierlot** [comment]
The issue was fixed after removing the service-worker.js file present on my app (created from this tutorial : https://dev.to/coorasse/the-progressive-rails-app-46ma), that looks to cause problem with OAuth only on Safari.

**Comment by smoyte** [comment]
I have this exact problem, but it also happens in Chrome. I would rather not remove the serviceworker entirely.

**Comment by lukasguldstoev** [comment]
> I have this exact problem, but it also happens in Chrome. I would rather not remove the serviceworker entirely.

Did you manage to solve this ? I have the same issue on chrome with google oauth2
