### ISSUE TITLE
How To: Use Recaptcha with Devise

### ISSUE THREAD

**Issue by mices** [heartcombo/devise#5409]
Your code `render :new` doesn't work in rails 6.1 I got it working using `redirect_to new_user_session_path` for logins but I'd rather use "resource" notation instead of explicitly naming the paths but I can't find an example Can you help

**Comment by nejdetkadir** [comment]
https://github.com/nejdetkadir/rails-boilerplate/commit/c5103748a8912fcb24b953e0979fcb39e6ec2b71
