### ISSUE TITLE
IdP initiated logout not working 

### ISSUE THREAD

**Issue by saranya-sanju** [heartcombo/devise#5417]
I'm using Rails 5.2 with Devise and Azure AD for SSO, Sign in process and SP initiated logout is working fine.

For IdP initiated logout, the user is not logged out of the session. The `session["saml_uid"]` is returning as nil and `validate_signature` is returning as false.

While accessing the session during LogoutRequest, facing the below issue

`#<ActionDispatch::Request::Session:0x7fb410fbc388 not yet loaded>`

I have the provided the below credentials for integrating Rails with Azure using `omniauh-saml`,
assertion_customer_service_url, idp_sso_target_url, idp_slo_target_url, idp_cert_fingerprint, issuer, slo_default_relay_state

Can you please help in getting the Rails session logged out while logging out in Azure?

**Comment by nashby** [comment]
Could you please provide a sample app that reproduces this issue?
