### ISSUE TITLE
Sign in after password reset always uses global configuration

### ISSUE THREAD

**Issue by mattr** [heartcombo/devise#5430]
## Overview

`sign_in_after_reset_password` is defined via `Devise::Model.config` which generates a class method on the resource class; however, the controller always uses the global configuration when determining whether the resource should be signed in after password reset.

### Example use case

`Admin` resource requires 2FA; allowing automatic sign in after password reset bypasses the 2FA check, so the admin must always sign in separately.

`User` resource does not require 2FA; the resource should be able to sign in automatically after password reset.

## Current behavior

Global config is always used for testing login after password reset.

```ruby
# devise/passwords_controller.rb

# L39
if Devise.sign_in_after_reset_password

# L56 (after_resetting_password_path_for(resource)
Devise.sign_in_after_reset_password ? after_sign_in_path_for(resource) : new_session_path(resource_name)
```

## Expected behavior

Devise should use the method on the resource class to allow configurable behavior for sign in after password reset.

```ruby
# devise/passwords_controller.rb

# L39
if resource_class.sign_in_after_reset_password

# L56
resource_class.sign_in_after_reset_password ? after_sign_in_path_for(resource) : new_session_path(resource_name)
```

PR to resolve this issue: https://github.com/heartcombo/devise/pull/5429

(Experiencing random failures for various ruby versions in GH actions...)

**Comment by nashby** [comment]
closed by https://github.com/heartcombo/devise/commit/ef6c73b2216939eba0302479297d60c64e4316b9
