### ISSUE TITLE
Password is updated with wrong `current_password` after resource update 

### ISSUE THREAD

**Issue by laertispappas** [heartcombo/devise#5433]
Hello, 

Can someone please explain to me how this test should behave: https://github.com/laertispappas/devise/commit/598da9ac86f7c76ea5a9e0963f4109540d6374c3

As is now if you call `save or update` method on the resource that is being authenticated after this call: https://github.com/heartcombo/devise/blob/main/lib/devise/models/database_authenticatable.rb#L107 the `assign_attributes ` will set the `enrypted_password` and any call to `user.save!` after that line will actually save the user with the new password. Although the current password was not validated.

This is a smell that happens on the caller for sure but from my perspective, I think that the library should also NOT keep track of the `encrypted_password` there, since it is not being validated,.

Any ideas thoughts? 
Thank you in advance.

**Comment by carlosantoniodasilva** [comment]
Closing, let us know if that's still a problem.
