### ISSUE TITLE
[Question] Is Main branch the new stable branch?

### ISSUE THREAD

**Issue by OskarEichler** [heartcombo/devise#5441]
Hey guys, great work on Devise!

We are currently discussing [here](https://github.com/gonzalo-bulnes/simple_token_authentication/issues/385) if the main branch of Devise is considered the new stable branch - the older stable branches haven't been updated in years, and the main branch is very actively maintained. 

Is the main branch considered stable and can be used as a dependancy, or should we wait for a new stable release that introduces Rails 7 support properly?

**Comment by carlosantoniodasilva** [comment]
Hey, sorry about not responding earlier. We've been using the `main` branch as stable now, yes, and just released a new version of Devise you can rely on. (but generally speaking main should be mostly stable, yes) Thanks!
