### ISSUE TITLE
Fix method redefined warnings

### ISSUE THREAD

**Issue by bkuhlmann** [heartcombo/devise#5459]
## Environment

- Ruby **ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21.2.0]**
- Rails **7.0.1**
- Devise **4.8.1**

## Current behavior

Hello. :wave: I've been seeing the following in my logs when running specs:

``` 
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:116: warning: method redefined; discarding old authenticate_user!
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:116: warning: previous definition of authenticate_user! was here
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:121: warning: method redefined; discarding old user_signed_in?
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:121: warning: previous definition of user_signed_in? was here
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:125: warning: method redefined; discarding old current_user
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:125: warning: previous definition of current_user was here
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:129: warning: method redefined; discarding old user_session
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:129: warning: previous definition of user_session was here
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:136: warning: method redefined; discarding old current_user
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:136: warning: previous definition of current_user was here
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:136: warning: method redefined; discarding old user_signed_in?
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:136: warning: previous definition of user_signed_in? was here
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:136: warning: method redefined; discarding old user_session
/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise/controllers/helpers.rb:136: warning: previous definition of user_session was here
```

## Expected behavior

I would expect those warnings to not be there but seems like methods are being constantly redefined?

## Steps to Recreate

You should be able to easily recreate this issue by launch your test suite with warnings enabled. For instance, in RSpec this looks like the following:

``` ruby
RSpec.configure do |config|
  config.warnings = true
end
```

**Comment by carlosantoniodasilva** [comment]
@bkuhlmann are you still experiencing those? I tried on an app here and didn't see them running some controller tests, but I did see a few others from devise related to instance variables not initialized that I can look at.

**Comment by bkuhlmann** [comment]
Hey Carlos, thanks. I'm afraid I'm no longer doing client work with Devise so I can't easily confirm this anymore. Back when I was working with this version of Devise, the behavior was constant. I would assume you'd see this in Devise's own test with RSpec warnings enabled? Maybe if you set `$VERBOSE = true` before running your test suite, you'd be able to easily recreate within Devise itself?

**Comment by carlosantoniodasilva** [comment]
Alright, appreciate the feedback, and sorry about taking just over 1 year to reply back 😅 

I will try with a few other variations of verbose / warnings, so far all I've got was those I mentioned above, and enabling [warnings here](https://github.com/heartcombo/devise/blob/41e2db212065f2a75a5d73e76d6eb8ecd53a6acf/Rakefile#L27) gives me a few method redefined from warden too, but that's about it. Thanks!

**Comment by bkuhlmann** [comment]
Yeah, thanks for getting back. :bow: Maybe this is already fixed in the current version and the issues is resolved (that'd be nice). Based on what you are seeing, it seems safe to close this for now so I'll do that. I can always reopen if I bump into this again. :wink:
