### ISSUE TITLE
recover password for multi-tenant / multi-domains

### ISSUE THREAD

**Issue by dvodvo** [heartcombo/devise#5471]
## Environment

- Ruby 2.6.1
- Rails 6.1.3
- Devise 4.7.3

## Current behavior
 
In development environment, the config has
```
  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
```

The application is multi-tenant -*but not using the apartment gem*- servicing multiple domains, both as 2nd and 3rd level domains.
```
third_1.example.com
third_2.example.com
another.com
```
The configuration for sending emails is via sendmail
```
config.action_mailer.smtp_settings = {
    address:              'smtp.fastmail.com',
    port:                 587,
    domain:               'domain.ws',
   [...]
```
Password is recoverable.  but should have a link corresponding the domain used in the request (one of the three above).
Instead it is combining  a third level domain `third_2` which effectively corresponds to the request but combines it with the smtp_settings for the domain, thus `third_2.domain.ws`. It certainly feels unexpected.

the application has a Site class with an attribute `host` which generates the URL.  How can this be used for setting the link for password recovery?

## Expected behavior
 URL domain for password recovery should respect the full domain of the action issuing the request for password resetting.

**Comment by supairish** [comment]
For our multi-tenant app (using ActsAsTenant) we do something like this

in config/initializers/devise.rb
```
Devise.setup do |config|
  config.parent_mailer = 'ApplicationMailer'
end
```

in app/mailers/application_mailer.rb
```
class ApplicationMailer < ActionMailer::Base
  before_action :set_mailers_url_host

  def set_mailers_url_host
    ActionMailer::Base.default_url_options[:host] = Current.tenant_host
  end
end
```

**Comment by dvodvo** [comment]
@supairish  suggestion is helpful in the ActsAsTenant context.

Wishing to avoid this, I followed a different route of commenting out default_url_options, providing a param on the form and setting it in devises passwords controller
```
def create
   ActionMailer::Base.default_url_options[:host] = params[:user][:host]
   super
end
```
