### ISSUE TITLE
How can i get the edit_password_url url from console ?

### ISSUE THREAD

**Issue by Ynventa** [heartcombo/devise#5482]
**This is what i have into a mailer file**

```
  def reset_password_instructions(record, token, opts = {})
    @token = token
    @resource = record

    if @resource.email.present?
      roadie_mail(to: @resource.email, subject: "Reset password instructions") do |format|
        format.html { render layout: 'mailer' }
      end
    else
      **url = edit_password_url(@resource, reset_password_token: @token)**
      su = ShortUrl.create({url: url})
      reset_url = short_urls_url(token: su.token)
      twilio_notification(@resource.phone, "Reset your password from this link #{reset_url}")
    end
  end
```

**And this is the error**
undefined method `edit_password_url' for #<NotificationMailer:0x000000000289d8>

Thank you

**Comment by jgigault-pa** [comment]
Hello, if you need to access URL helper from outside of controllers and views, you can use: `Rails.application.routes.url_helpers.edit_password_url(...)`

**Comment by carlosantoniodasilva** [comment]
Yes, accessing via the app routes url helpers is how you'd do it outside of a controller or view. Thanks @jgigault-pa!
