### ISSUE TITLE
NameError: uninitialized constant DeviseController

### ISSUE THREAD

**Issue by marti-1** [heartcombo/devise#5486]
## Environment

- Ruby **2.7.5**
- Rails **7.0.2.4**
- Devise **4.8.1**

## Current behavior

Running `rails app:update` gives the following error at the end:

```
rails aborted!
NameError: uninitialized constant DeviseController
/Users/martynas/projects/bend/config/initializers/devise_permitted_parameters.rb:17:in `<main>'
/Users/martynas/projects/bend/config/environment.rb:5:in `<main>'
Tasks: TOP => active_storage:update => environment
(See full trace by running task with --trace)
```

## Expected behavior

No error.

**Comment by carlosantoniodasilva** [comment]
@marti-1 you still having problems with this? I'm not sure what would cause it, but it seems like it's trying to load `DeviseController` from an initializer and I'm not sure that's a good thing, as app code shouldn't be eagerly loaded in initializers like that, generally speaking.

Can you show the contents of `devise_permitted_parameters.rb`?

**Comment by carlosantoniodasilva** [comment]
Please report back if you're still having issues, and we can try looking into it.
