### ISSUE TITLE
Rails 7.0 Sign Up no more saving password on alias column

### ISSUE THREAD

**Issue by vBalatroni** [heartcombo/devise#5488]
## Environment

- Ruby **[3.1.2]**
- Rails **[7.0.2]**
- Devise **[4.8.1]**
- Database **postgresql**

## Premise
Hello, i'm facing a problem linked to registrations:
In my app i need to have, or better, **must have** as main  password column a column called **Password** ( with capitalized P).

## Expected behavior
So I found a workaround using an `alias_attribute` like that:
```
devise :database_authenticatable, :registerable, :confirmable,
:recoverable, :rememberable, :validatable, :encryptable, encryptor: :sha512
  
alias_attribute :encrypted_password, :Password
```
  
It worked good and my password with sha512 hash was correctly stored in the targeted column **Password**. 

## Current behavior
Now, after updating Rails v i found out that this Password column is not filled anymore with encrypted_password.

## Conclusions:
This solution worked until i changed from rails 6.1 to rails 7, or better, until i changed `config.load_defaults ` from `6.1` to `7.0`

Let me know if you need more details, thanks

**Comment by carlosantoniodasilva** [comment]
Hello @vBalatroni, have you been able to figure out what was going on here, if it was Devise specific? If not, we might need to build a sample app to test it out.

**Comment by vBalatroni** [comment]
Hello @carlosantoniodasilva, my needs changed by the time i opened the issue but as i can remember the problems was still there

**Comment by carlosantoniodasilva** [comment]
@vBalatroni thanks for the update.

I tried creating a test app with the setup you showed:

```ruby
devise :database_authenticatable, :registerable, :confirmable,
:recoverable, :rememberable, :validatable, :encryptable, encryptor: :sha512
  
alias_attribute :encrypted_password, :Passwor
```

Including both `devise`, `devise-encryptable`, and tested signing up / logging in, and via the console as shown below:

```ruby
 > u.valid_password? 'carlos@test.com'
=> false
 > u.valid_password? '123456'
=> true
 > u.password = 'carlos@test.com'
=> "carlos@test.com"
 development  irb(main):014:0> u.save!
  TRANSACTION (0.1ms)  begin transaction
  User Update (0.6ms)  UPDATE "users" SET "Password" = ?, "password_salt" = ?, "updated_at" = ? WHERE "users"."id" = ?  [["Password", "[FILTERED]"], ["password_salt", "[FILTERED]"], ["updated_at", "2023-02-24 13:58:29.737294"], ["id", 1]]
  TRANSACTION (0.9ms)  commit transaction
=> true
 > u.reload
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
=> #<User id: 1, email: "carlos@test.com", Password: [FILTERED], string: nil, created_at: "2023-02-24 13:51:56.821924000 +0000", updated_at: "2023-02-24 13:58:29.737294000 +0000">
 > u.valid_password? '123456'
=> false
 > u.valid_password? 'carlos@test.com'
=> true
```

Everything worked with the aliased attribute, as you can see I don't have an `encrypted_password` column but rather a `Password` one:

```ruby
 User.column_names
=>
["id",
 "email",
 "Password",
 "password_salt",
 "string",
 "reset_password_token",
 "reset_password_sent_at",
 "remember_created_at",
 "confirmation_token",
 "confirmed_at",
 "confirmation_sent_at",
 "unconfirmed_email",
 "created_at",
 "updated_at"]
```

This is working the latest Devise and Rails:

```ruby
> Rails.version
=> "7.0.4.2"
 > require 'devise/version'
=> true
 > Devise::VERSION
=> "4.9.0"
```

Maybe there was something unique to your setup that made it not work at the time. For now I'm going to consider this one closed. Thanks!
