### ISSUE TITLE
Is there a namespace conflict with an 'Asset' model?

### ISSUE THREAD

**Issue by jasper502** [heartcombo/devise#5489]
## Environment

- Ruby ruby 3.1.1p18
- Rails 7.0.2.3
- Devise 4.8.1

## Current behavior

I have a `Location` model with the stock CRUD actions / tests.  Works fine in development and production and the test all pass.

Added an `Asset` model which is an exact clone of Location besides belonging to the location model.  Works fine in development and production.  The issue is that the `current_user` is only being set in the **index** and **create** actions.  In all other tests `current_user` returns nil.  I have double checked everything for typos etc.  My fixtures are fine.  I added a binding.irb in a few spots in my controllers and I I can manually sign_in the user:

```
irb(#<AssetsController:0x0000000114df70b8>):006:0> current_user
=> nil
irb(#<AssetsController:0x0000000114df70b8>):007:0> sign_in User.find_by(email: 'member@example.com')
=> #<User id: 820312697, email: "member@example.com", first_name: "Company", last_name: "Member", time_zone: "America/Chicago", accepted_terms_at: "2022-05-03 19:17:49.000000000 +0000", accepted_privacy_at: "2022-05-03 19:17:49.000000000 +0000", announcements_read_at: nil, admin: nil, created_at: "2022-05-03 19:17:49.555195000 +0000", updated_at: "2022-05-03 19:17:49.555195000 +0000", invitation_token: nil, invitation_created_at: nil, invitation_sent_at: nil, invitation_accepted_at: nil, invitation_limit: nil, invited_by_type: nil, invited_by_id: nil, invitations_count: 0, preferred_language: nil, otp_required_for_login: nil, otp_secret: nil, last_otp_timestep: nil, otp_backup_codes: [], skip_default_account: false, terms_of_service: nil>
irb(#<AssetsController:0x0000000114df70b8>):008:0> current_user
=> #<User id: 820312697, email: "member@example.com", first_name: "Company", last_name: "Member", time_zone: "America/Chicago", accepted_terms_at: "2022-05-03 19:17:49.000000000 +0000", accepted_privacy_at: "2022-05-03 19:17:49.000000000 +0000", announcements_read_at: nil, admin: nil, created_at: "2022-05-03 19:17:49.555195000 +0000", updated_at: "2022-05-03 19:17:49.555195000 +0000", invitation_token: nil, invitation_created_at: nil, invitation_sent_at: nil, invitation_accepted_at: nil, invitation_limit: nil, invited_by_type: nil, invited_by_id: nil, invitations_count: 0, preferred_language: nil, otp_required_for_login: nil, otp_secret: nil, last_otp_timestep: nil, otp_backup_codes: [], skip_default_account: false, terms_of_service: nil>
```
In my test helper I have `sign_in users(:member)`

## Expected behavior

It's expected to sign_in the user for both models and all tests.

Before I dig deeper is there perhaps a namespace conflict with my 'Asset' model and Devise?  Very odd that only the index and and create actions have the error.

**Comment by carlosantoniodasilva** [comment]
There's nothing specific related to the name "Asset" in Devise, and searching for that word in the source code only returns a few instances inside the rails test app used by the test suite. If there's a conflict could be with Rails, but I can't think of anything off the top of my head.

If you can try to create a separate app that shows the issue and has devise installed, we may be able to help look into it some more.

**Comment by jasper502** [comment]
Thanks - I figured so.  I am going to try that next to see if it is Devise and I can reproduce the issue with a clean app.
