### ISSUE TITLE
Devise warden authentication allows GET query params takes precedence over POST params

### ISSUE THREAD

**Issue by clubbavi** [heartcombo/devise#5525]
- Ruby 2.6.6
- Rails 6.0.2
- Devise 4.8.1

## Current behavior

I am using a custom session controller.

Sign_in form contains email & password, when we submit, it's a POST request.

But from the Burp Suite which is used for Pen-testing activity: We can also send the different email & password in the url itself as a query string.

And devise seems to take url query parameters as the precedence over POST parameters.

In the below example:
In the form(POST param), I am sending email(abc@abc.com) & password(pwd).  --> This is wrong password
In the get param, I am sending email(abc@abc.com) & password(password) --> This is correct password

`POST /users/sign_in?locale=in&authenticity_token=XMmnt9g2jobCbBtyP2oUbHIUmfGwcpCLB2Ye0FlQyK65sbbz3yXHIH5osOObs9hZGmBp5ujPbmbbcpWY4O6omw%3D%3D&user%5Bemail%5D=abc%40abc.com&user%5Bpassword%5D=password&commit=Login HTTP/1.1
Host: localhost:4000
Content-Length: 214
Cache-Control: max-age=0
sec-ch-ua: "Chromium";v="105", "Not)A;Brand";v="8"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Upgrade-Insecure-Requests: 1
Origin: http://localhost:4000
Content-Type: application/x-www-form-urlencoded
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:4000/users/sign_in
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cookie: _sso_session=LEqy1%2sdsfddsfsdfsdff7QhgkDs3DlzMAz2ektOb9%2BaCjxFZ4gt0Bi9URZ5fU41szRJh089juOa01Ra7HKe69ULRMHVlla90AagE%2Bc0PDebSHAh5iG2wIGqwJfoGww9AXCvE29fn8pKdsdsd7gpbRgPz7WO9bQcauAa7VV1Gu842ECI6T7SOymlwgCi7U%2FnQoL007pz6vDFXdErvd9aQQrSkJQDugVKGKxe6hcKb2iFdUztVPEh4AiIgP%2FuV44UlAxwKj4tB%2FAsmAFeBKVD5IRW8pNh59oGgJtxCgrfzZXC5%2BpfkC30T1QU%2B43FkVLBhHHJDyHw3hC6%2FJrMAIr%2FfucMYT82%2BCXKEjMw5J8rjjeS%2BcbWKWojlMkU9a5%2BHfqA7YD%2BkBfCi%2FigJ9Lgq8fLbGkFhOyOouhRi8MEm%2FM9at4Qe8ZiGFq6AHRa4EcQ%3D--%2FAGuG14oybdtocBt--EmZ8UhRZoBktUfXseITKgQ%3D%3D
Connection: close
authenticity_token=XMmnt9g2jobCbBtyP2oUbHIUmfGwcpCLB2Ye0FlQyK65sbbz3yXHIH5osOObs9hZGmBp5ujPbmbbcpWY4O6omw%3D%3D&user%5Bemail%5D=abc%abc.com&user%5Bpassword%5D=pwd&commit=Login`

## Expected behavior

It should not give precedence to the GET Query string.

I tried removing get params by:
`request.GET.delete('key')`

but still it accepting the correct password passed in the query string & logs in.

Any suggestions ?

**Comment by carlosantoniodasilva** [comment]
I believe this is [Rails behavior when merging to a single params hash](https://github.com/rails/rails/blob/d53dc868869f973c7ee0bbcdaacfc0239f261773/actionpack/lib/action_dispatch/http/parameters.rb#L55), devise does not prefer one or the other, it simply uses the provider request params access via Rails (similar to how you'd access params in any controller). If you have considerations about this behavior, I'd recommend opening an issue there. (just make sure to search around for any other possible related issue)
