### ISSUE TITLE
Custom Controller View Directory

### ISSUE THREAD

**Issue by natu12** [heartcombo/devise#5526]
Quick question from the latest readme.md

In the section "**Configuring controllers**", after you've generated a custom controller it says: 

_3. Copy the views from devise/sessions to users/sessions. Since the controller was changed, it won't use the default views located in devise/sessions_

I haven't changed the directory of devise/sessions and it is still rendering the view properly. Is this step necessary? Thanks.

**Comment by natu12** [comment]
Currently using Rails 7, and latest Devise 4.8.1

**Comment by carlosantoniodasilva** [comment]
@natu12 it's not strictly necessary, no... the wording there can be changed to mention that it's maybe more of a recommendation, I'll update it.

I explained a bit more in this comment: https://github.com/heartcombo/devise/issues/5532#issuecomment-1434945330, but basically Rails will lookup views in the inheritance chain using the view paths, so it will first try to find them in `users/sessions`, then `devise/sessions` (both in your app), then inside devise gem `devise/sessions`.

Thanks!
