### ISSUE TITLE
User not logged out after restart docker

### ISSUE THREAD

**Issue by gonzalo944** [heartcombo/devise#5528]
## Environment

- Ruby **2.5.5**
- Rails **6.0.2**
- Devise **4.8.0**

## Current behavior
Hello guys, I have a problem with my app, the app is build with docker and the rememberable option is not configurated in user.rb file, when i stop the container and start it again the user is still logged in the system. Cleaning the cookies or cache doesn't work, the user is still logged in.

**user.rb**
class User < ApplicationRecord
  audited
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable, :trackable

## Expected behavior
When the container restarts the user should be logged out and asked to sign in again into the system.

**Comment by carlosantoniodasilva** [comment]
There's no reason for the user to be logged out if the containers are restarted, as the session cookie may still be alive for that browser session -- that's what you'd control whether they're logged in or not (despite rememberable being off).

However, clearing the cookies should log them out I believe. You still having problems with that?
