### ISSUE TITLE
Devise error messasge do not shows proper

### ISSUE THREAD

**Issue by TangMonk** [heartcombo/devise#5530]
Fresh install Rails 7 and and devise 4.8.1

If I login in with wrong password, a flash error message will show up to page, like following screenshot:

[![enter image description here][1]][1]

But the weird thing is that flash error message is append to the end of html, like following screenshot:

[![enter image description here][2]][2]

the `_error_message.html.erb` is located in `app/views/deivse/shared`:

    <% if resource.errors.any? %>
    <div class="alert alert-primary" role="alert">
      <div id="error_explanation">
        <h2>
          <%= I18n.t("errors.messages.not_saved",
                     count: resource.errors.count,
                     resource: resource.class.model_name.human.downcase)
           %>
        </h2>
        <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <% end %>

I try to change above error view file, but the flash message still not change, even I empty the error view file.

  [1]: https://i.stack.imgur.com/9W9am.png
  [2]: https://i.stack.imgur.com/fv6kn.png

**Comment by ksnitsky** [comment]
Adding `data: { turbo: false }` fixed the problem for me, but now the whole page reloads when the form is submitted.

Looks like a problem with `turbo_stream` rendering.

**Comment by scratchoo** [comment]
same issue here! any solution?

**Comment by gardnerapp** [comment]
see [Issue](https://github.com/heartcombo/devise/issues/5446) for other ways to fix this and [this pull request](https://github.com/heartcombo/devise/pull/5440)

**Comment by carlosantoniodasilva** [comment]
The main branch should contain all that's necessary for fully working with Turbo now, which should fix this. A new version will be released soon, but feel free to test it out from the main branch in the meantime, and report back on any issues. Thanks.
