### ISSUE TITLE
Devise navigation links no longer working with turbo

### ISSUE THREAD

**Issue by bluestorm21** [heartcombo/devise#5542]
I am running on rails 7.0.4 and ruby 3.0.2

I was adding turbo:false to all my devise forms, and it was fine, however now somehow all the navigation links in devise/shared/_links.html.erb are not working with turbo effect, when I click any, the page does a full loading

Is this something that was intentionally added or I have some issue with my code?

The rest of my app is just working fine with turbo, only devise views have that issue.

**Comment by parkerleblanc01** [comment]
I'm on rails 7 and followed this guide to get everything to work as expected: https://dev.to/efocoder/how-to-use-devise-with-turbo-in-rails-7-9n9

**Comment by carlosantoniodasilva** [comment]
The main branch should contain all that's necessary for fully working with Turbo now, which should fix this. A new version will be released soon, but feel free to test it out from the main branch in the meantime, and report back on any issues. Thanks.
