### ISSUE TITLE
generate devise User command hung up on inflector method

### ISSUE THREAD

**Issue by dvodvo** [heartcombo/devise#5544]
- Ruby 3.1.2
- Rails 7.0.4
- Devise 4.8.1

## Current behaviour
Clean install. (*motive: been having issues with authenticating users in tests*)
• altered gem list
• ran `rails generate devise:controllers users`
• attempted `rails generate devise User name_last name_first admin:boolean manager:boolean date_of_birth:date`
then
• attempted `rails generate devise User`

In both cases:
```
/Users/jerdvo/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/inflector/methods.rb:280:in `constantize': uninitialized constant User (NameError)

      Object.const_get(camel_cased_word)
            ^^^^^^^^^^
Did you mean?  Users
	from /Users/jerdvo/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
	from /Users/jerdvo/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/devise-4.8.1/lib/devise.rb:320:in `get'
```

## Expected behaviour
The documentation clearly [specifies](https://github.com/heartcombo/devise#getting-started) 
`In the following command you will replace MODEL with the class name used for the application’s users (it’s frequently User but could also be Admin).`

This behaviour did not exist in the past - I believe (but do not rely 100% on memory) that command has been used so many times previously and generated the relevant migrations & classes. It has appeared on several occasions recently with the above versions. *Frankly, I do not recall how this was overcome in these recent occurances.*

sandboxed in the following [repository](https://github.com/dvodvo/deviset).

**Comment by dtakeshta** [comment]
@dvodvo if you remove the `devise_for` from your routes, the generator should work.  The generator will add this into your routes and you can modify as needed.

```
devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

**Comment by nashby** [comment]
As @dtakeshta said (thanks btw!) you have to have model defined before you can use `devise_for` router. We could potentially improve it but I couldn't find any more issues regarding this so I'm going to close this for now.
