### ISSUE TITLE
Wiki: how about mentioning "Cancel my account" link?

### ISSUE THREAD

**Issue by JunichiIto** [heartcombo/devise#5555]
Just suggestion, how about mentioning "Cancel my account" link in https://github.com/heartcombo/devise/wiki/How-To:-Upgrade-to-Devise-4.9.0-%5BHotwire-Turbo-integration%5D#data-confirm-vs-data-turbo-confirm ? Some people might want to provide  "Cancel my account" link instead of button:

```erb
<%# works with rails-ujs but does not work with Turbo %>
<%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %>

<%# works with Turbo but does not work with rails-ujs %>
<%= link_to "Cancel my account", registration_path(resource_name), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>

<%# works with both %>
<%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?", turbo_method: :delete, turbo_confirm: "Are you sure?" }, method: :delete %>
```

In addition, you might want to revert https://github.com/heartcombo/devise/pull/5554 and keep `<p>` tag...

```erb
<p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?", turbo_method: :delete, turbo_confirm: "Are you sure?" }, method: :delete %></p>
```

<img width="459" alt="Screenshot 2023-02-15 at 8 59 46" src="https://user-images.githubusercontent.com/1148320/218890640-33a13f47-4a98-415f-bf4f-af67437c4f88.png">

**Comment by carlosantoniodasilva** [comment]
I updated the wiki to mention both `button_to` and `link_to` so we can cover more ground in the examples there, appreciate the suggestion. 👍

I think we should stick to `button_to` in Devise for compatibility reasons, plus it's been like that for about 10 years now: https://github.com/heartcombo/devise/pull/2210, and I like the reasons for the original change explained [in this comment](https://github.com/heartcombo/devise/pull/2210#issuecomment-12166270) there: use buttons for actions, links for navigation. Thanks!

**Comment by JunichiIto** [comment]
Thank you for your updating of wiki! 

> I like the reasons for the original change explained https://github.com/heartcombo/devise/pull/2210#issuecomment-12166270 there: use buttons for actions, links for navigation. Thanks!

I agree with the opinion too. 🙂
