### ISSUE TITLE
undefined method 'encryptor='

### ISSUE THREAD

**Issue by cryptogopher** [heartcombo/devise#5566]
## Environment

- Ruby **2.7**
- Rails **7.0.4**
- Devise **4.9.0**

## Current behavior

When trying to run `rails` after `$ rails generate devise:install` and changing _config/initializers/devise.rb_ I get error
```
$ bundle exec rails generate --help
Traceback (most recent call last):
...
[...]/config/initializers/devise.rb:241:in `block in <top (required)>': undefined method `encryptor=' for Devise:Module (NoMethodError)
```

## Expected behavior

There should be no error.

It looks like `encryptor=` has been removed since 3.1.0 (https://github.com/heartcombo/devise/commit/7e96bac6a48abbf6ac761aab9c01e7efc838b5c1), but config template has not been updated.

`config.encryptor` should be removed from config template.

**Comment by carlosantoniodasilva** [comment]
[`config.encryptor` is commented out in the template](https://github.com/heartcombo/devise/blob/7d1dc56fdba2402c452c4224567077b23184637e/lib/generators/templates/devise.rb#L233-L241)

You need `devise-encryptable` if you want to try that option though.

> and changing config/initializers/devise.rb

What changes have you made? Maybe uncommented out that option by mistake?

**Comment by cryptogopher** [comment]
I uncommented it intentionally. First I set it to :sha512 - got error. Then set it to :bcrypt - also got error.

It is indeed stated that I need additional gem when setting it to anything other than bcrypt. But when I set it to bcrypt the error was still there.

**Comment by carlosantoniodasilva** [comment]
Gotcha. You don't need the option to use `bcrypt`, that's used by default unless you install `devise-encryptable` and set that config to something else then. (otherwise it's just assumed bcrypt)
