### ISSUE TITLE
uninitialized constant Devise::SessionsController

### ISSUE THREAD

**Issue by arslbbt** [heartcombo/devise#5582]
## Environment

- Ruby **[3.2.1]**
- Rails **[7.0]**
- Devise **[4.9.2]**
- Activeadmin **[2.13]**

## Current behavior
I have rails application that was built on ruby 2.7.1, rails 5.2, devise 4.7.2, and activeadmin 2.9.0. i want to update it to the current versions. when i update the ruby to 3.2.1, rails to 7.0, devise to 4.9.2, and activeadmin to 2.13, i got the  **uninitialized constant Devise::SessionsController** in gem lib file `.rvm/gems/ruby-3.2.1/gems/activeadmin-2.13.1/lib/active_admin/devise.rb:54:in <module:Devise>': uninitialized constant Devise::SessionsController (NameError)`

## Expected behavior
Evertyting need to be work wihout error

**Comment by carlosantoniodasilva** [comment]
I'd recommend doing smaller upgrades and not going all at once to the latest. You could for example upgrade Devise without upgrading everything else first.

It sounds like this error is coming from active admin though, not Devise, so I'd recommend reporting there. If you can provide a sample app showing the error I'd be happy to try looking into it more, otherwise there's not much else I can do without additional info, stack traces, and/or a sample app.

**Comment by Iamyuvraj143** [comment]
I have also faced the same issue. I had 2FA integration for active admin and it was working fine for me.  but I have to upgrade my ruby and rails version to ruby 3.2.1 and rails 7
When I updated this I faced the same issue it started giving
rake aborted!
NameError: uninitialized constant Devise::SessionsController (NameError)

    class SessionsController < ::Devise::SessionsController
    
    **Solution** 
    # app/controllers/admin/custom_sessions_controller.rb
    
    `# app/controllers/admin/custom_sessions_controller.rb
module Admin
  class CustomSessionsController < ActiveAdmin::Devise::SessionsController
    include ::ActiveAdmin::Devise::Controller

    def create
      super do |resource|
        # Generate and save OTP
        resource.generate_and_save_otp
        puts "Mobile Verification code for admin login is #{resource.mobile_otp}"
        if resource.mobile_otp.present?
          redirect_to admin_otp_verification_path(resource_id: resource.id) and return
        end
      end
    end
  end
end
`

routes.rb file

`custom_config = ActiveAdmin::Devise.config.merge(
  controllers: { sessions: 'admin/custom_sessions' }
)

devise_for :admin_users, custom_config

ActiveAdmin.routes(self)`
