### ISSUE TITLE
Deprecation warning: calling `DeprecatedConstantAccessor.deprecate_constant` without a deprecator

### ISSUE THREAD

**Issue by marcoroth** [heartcombo/devise#5589]
## Environment

- Ruby 3.2.1
- Rails Edge after commit [`2f08f9a`](https://github.com/rails/rails/commit/2f08f9ac2ca6a130498fe192bdf28c8cb06617aa)
- Devise 4.9.2

## Current behavior

```shell
DEPRECATION WARNING: DeprecatedConstantAccessor.deprecate_constant without a deprecator is deprecated (called from <module:Authenticatable> at ~/.anyenv/envs/rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/devise-4.9.2/lib/devise/models/authenticatable.rb:65)
```

Context: https://github.com/rails/rails/pull/47354

## Expected behavior

The gem shouldn't log a deprecation warning

**Comment by marcoroth** [comment]
What is devise's maintenance policy for maintained Rails versions?  I'm wondering if we can remove [`Devise::DeprecatedConstantAccessor`](https://github.com/heartcombo/devise/blob/4b72064bfcf076478c5c87818b9536b203f6584f/lib/devise/rails/deprecated_constant_accessor.rb) and require Rails 5.1+ in 5.0, looking at the comment:
> Copy of constant deprecation module from Rails / Active Support version 6, so we can use it 
> with Rails <= 5.0 versions. This can be removed once we support only Rails 5.1 or greater.`

**Comment by rafaelfranca** [comment]
This should be fixed on master now

**Comment by miharekar** [comment]
Any ETA when this'll get released? It's quite noisy in Rails 7.1 😅

**Comment by contentfree** [comment]
@rafaelfranca What's stopping a new release (that will then include this fix)? Like miharekar said: It's noisy in Rails 7.1.

**Comment by lmansur** [comment]
For those wondering, Devise 4.9.3 was released with the fix for this back in October 2023: https://rubygems.org/gems/devise/versions/4.9.3
