### ISSUE TITLE
`configure_warden!': undefined method `failure_app=' for nil:NilClass (NoMethodError)        warden_config.failure_app   = Devise::Delegator.new

### ISSUE THREAD

**Issue by Arun-StarApps** [heartcombo/devise#5605]
Hi everyone 

i've created my one gem which have engine on it 
`engine.rb`
```rb
module Test
    class Engine < ::Rails::Engine
      isolate_namespace Test
    end
  end
  
```
`tests_controller.rb`
```rb

module Test
  class TestsController < ActionController::Base
    include ActionDispatch
    def test 
        puts "inside test controller"
    end
  end
end

```

`routes.rb`
```rb


Test::Engine.routes.draw do
     post 'test' => 'tests#test'
end

```
## Current behavior

After installing test gem i'm getting error 
`configure_warden!': undefined method `failure_app=' for nil:NilClass (NoMethodError)        warden_config.failure_app   = Devise::Delegator.new`

Getting above error only when 'test' gem installed after 'device' gem but when i'm moving `test`
 gem above `devise` gem it's working file.

**Comment by nashby** [comment]
Hey! Could you please provide a sample app that reproduces this issue?

**Comment by kpvarma** [comment]
I encountered a similar issue where Warden was throwing errors like:

1. undefined method `failure_app=' for nil:NilClass (NoMethodError)
2. undefined method `map' for #<Rails::Configuration::MiddlewareStackProxy>

After a lot of debugging, I realized the root cause: I created the Ruby gem using bundler instead of generating it as a Rails plugin.

Steps to Reproduce
	1.	Create a Ruby gem using bundler gem my_gem.
	2.	Configure it to work as a Rails engine, including middleware or routes.
	3.	Add the gem to a Rails app (Gemfile) with a path directive.
	4.	Attempt to use middleware like Warden or other Rails-specific components.

What Went Wrong
	•	A gem generated with bundler gem lacks the configurations and structure Rails plugins typically require.
	•	This caused Warden to fail because certain Rails-specific hooks (like initializing middleware stacks or loading properly as an engine) were missing.
