### ISSUE TITLE
I18n is incomplete

### ISSUE THREAD

**Issue by jpgeek** [heartcombo/devise#5619]
## Environment

- Ruby **ruby 3.1.2p20**
- Rails **7.0.7**
- Devise **4.9.2**

## Current behavior

Many of the templates are not I18n enabled.  For example in 
`devise/registrations/edit.html.erb`
The line:
`<h2>Edit <%= resource_name.to_s.humanize %></h2>`

does not translate the term "Edit".  

## Expected behavior

All text should be translated.  The above line would be something like:
`<h2>I18n.t('devise.registrations.edit') <%= resource_name.to_s.humanize %></h2>`

**Comment by carlosantoniodasilva** [comment]
We've historically decided against translated the views, so we don't have any I18n in there. It's easy to copy the views over or use one of the 3rd-party gems that provide this functionality. (this is something I've considered to change more recently and introduce i18n, but I'm not ready to make that commitment, so for now the decision is still the same, no i18n in the views.)

**Comment by jpgeek** [comment]
Understood.  Will skip the PR then.  Appreciate the quick response and your work on Devise.
