### ISSUE TITLE
undefines method utc in reset_password_period_valid? method

### ISSUE THREAD

**Issue by jdonadob** [heartcombo/devise#5646]
undefines method utc for String.  Recovering password, "reset_password_sent_at" variable contains a String value instead of Datetime value.

devise (4.9.2)
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]
Rails 7.0.6

**Comment by carlosantoniodasilva** [comment]
:+1: cool, glad I could help.
