### ISSUE TITLE
strong params not working as per "lazy way" instructions

### ISSUE THREAD

**Issue by mices** [heartcombo/devise#5650]
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  include PublicActivity::StoreController

  WillPaginate.per_page = 75

   protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :name, :first_name, :last_name, :middle_name,  :birth_date, :birth_place_country, :birth_place_state, :birth_place_city, :country, :state, :city, :gender, :band, :genre, :password, :password_confirmation])
    end

**Comment by nashby** [comment]
I tested it with the latest version of Devise, and it works as expected. Feel free to provide a sample app that reproduces this issue, and I'll reopen it. Thanks!
