### ISSUE TITLE
How to prevent to send a confirmation email when email field is updated ? #903

### ISSUE THREAD

**Issue by adrys-lab** [heartcombo/devise#5671]
## Environment

- Ruby **3**
- Rails **7**
```
    devise (4.9.3)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise_invitable (2.0.7)
      actionmailer (>= 5.0)
      devise (>= 4.6)
```

In our application we are sending a confirmation email (OLD email, saying email has changed, NEW email confirm your email) when a user updates his email.

Now this is handled by another system and we want the legacy service stop sending such notification (NEW email confirm your email),

is there a standalone configuration to prevent that ?

Could it be this option ?

config.reconfirmable = true
We want ONLY avoid sending emails when email update (meaning from [xx@xx.com](mailto:xx@xx.com) to [yy@yy.com](mailto:yy@yy.com)),

but keep sending emails on NEW SIGN IN.

i would like to find a proper configuration that allows us to do so, instead of hijacking it like the snipped code below:

```
  def confirmation_instructions(record, token, opts = {})
    return if opts[:action] == "email_update"
    
    XXXX
  end
```

**Comment by carlosantoniodasilva** [comment]
I think you're looking for [`skip_confirmation_notification!`](https://github.com/heartcombo/devise/blob/e2242a95f3bb2e68ec0e9a064238ff7af6429545/lib/devise/models/confirmable.rb#L159-L163) before you update the user attributes with the new email.

Note that they'll still require the new email to be confirmed, just won't get the email notification. If you don't want that, you can maybe use [`skip_reconfirmation!`](https://github.com/heartcombo/devise/blob/e2242a95f3bb2e68ec0e9a064238ff7af6429545/lib/devise/models/confirmable.rb#L165-L167), or maybe just disable the entire `reconfirmable` feature like you mentioned.
