### ISSUE TITLE
Example for 7.1.0 is effectively useless

### ISSUE THREAD

**Issue by AlvesJorge** [heartcombo/devise#5684]
First of all thank you for your work on this gem! 

I have an issue with the devise example for Rails [7.1.0](https://github.com/jasonnoble/rails_7_1_devise_example), you will find it has:

- Started a Rails app;
- Added the gem;
- Ran the installer and followed its instructions;
- Nothing else.

There is no actual example on how the Gem is used at all within a basic application, instead it is only showing us what it looks like to have the gem installed. 

This is effectively useless, and will waste the time of everyone who opens this example.

**Comment by carlosantoniodasilva** [comment]
Thanks, that example is not something Devise / heartcombo is related with in any way, so if you feel like their Readme doesn't show enough steps to help someone get started, feel free to open an issue there.

If you feel like you can improve Devise's readme, PRs are welcome.

**Comment by AlvesJorge** [comment]
Hi @carlosantoniodasilva 
The example is linked in the heartcombo/devise wiki, so it is related.
https://github.com/heartcombo/devise/wiki/Example-Applications

**Comment by AlvesJorge** [comment]
No need to promise, I just wanted to point that out. All the best!
